### ISSUE TITLE
Changed data type for hashes stored in database from String to Binary

### ISSUE THREAD

**Issue by elhoim** [viper-framework/viper#123]
This would allow to save a tremendous amount of space.
Lets say md5 + crc32 + sha1 + sha256 + sha512 take 272 bytes to store as ASCII strings, but only 30 bytes as binary.

**Comment by Rafiot** [comment]
Is it really a problem? To me, it adds lots of hassle (encoding/decoding) for nothing: the size of a sample is so much bigger than the 240 bytes you will gain that I don't think it is something we should do.
