### ISSUE TITLE
Clamav can't connect in Viper

### ISSUE THREAD

**Issue by stormproof** [viper-framework/viper#165]
I get the following message when calling on clamav inside of Viper. Any suggestions would be apreciated. 

stormproof-analysis viper 9699b28a653395444d05c8c6030d9ec738661eede9d3ca44fb1615bdc52dfa0b > clamav
[!] Daemon connection failure, Could not reach clamd using unix socket (/var/run/clamav/clamd.ctl)

More details

Sat Nov 15 02:42:15 2014 -> Received signal: wake up
Sat Nov 15 02:42:15 2014 -> ClamAV update process started at Sat Nov 15 02:42:15 2014
Sat Nov 15 02:42:15 2014 -> WARNING: Your ClamAV installation is OUTDATED!
Sat Nov 15 02:42:15 2014 -> WARNING: Local version: 0.98.1 Recommended version: 0.98.4
Sat Nov 15 02:42:15 2014 -> DON'T PANIC! Read http://www.clamav.net/support/faq
Sat Nov 15 02:42:15 2014 -> main.cvd is up to date (version: 55, sigs: 2424225, f-level: 60, builder: neo)
Sat Nov 15 02:42:15 2014 -> daily.cld is up to date (version: 19630, sigs: 1260256, f-level: 63, builder: neo)
Sat Nov 15 02:42:15 2014 -> bytecode.cvd is up to date (version: 242, sigs: 46, f-level: 63, builder: dgoddard)

**Comment by Rafiot** [comment]
Merged.
