### ISSUE TITLE
Array slice typos and more in pehash module

### ISSUE THREAD

**Issue by kryptpt** [viper-framework/viper#217]
There are some array slice typos in the pehash code due to the confusing in the python's array slice notation.

I'll give an example. 

pehash pseudo-code says:
hash[0] := characteristics[0..7] xor characteristics[8..15] 

```python 
#what was expected
img_chars_xor = img_chars[0:8] ^ img_chars[8:16]
````
```python 
#what pehasher.py does
img_chars_xor = img_chars[0:7] ^ img_chars[8:15]
```
Article's link https://www.usenix.org/legacy/event/leet09/tech/full_papers/wicherski/wicherski_html/

**Comment by kevthehermit** [comment]
Fixed with https://github.com/viper-framework/viper/pull/341
