### ISSUE TITLE
[API] Add comments to a file

### ISSUE THREAD

**Issue by deralexxx** [viper-framework/viper#231]
It should be possible to add a new comment to a file using the API.

Will see if I have the time to work it out (should not a be a big thing).

Any wishes?

**Comment by kevthehermit** [comment]
Let me add the new web commands fuñctions in to the api. Will make it
easier to add functuons like this

**Comment by deralexxx** [comment]
ok!

**Comment by botherder** [comment]
Any update on this ticket?

**Comment by kevthehermit** [comment]
on it now

**Comment by kevthehermit** [comment]
Pull here https://github.com/botherder/viper/pull/256
