### ISSUE TITLE
radare2 support must use the r2pipe api

### ISSUE THREAD

**Issue by radare** [viper-framework/viper#235]

**Comment by botherder** [comment]
I'm not sure really, cause I wouldn't want to replace the already wonderful shell you guys created. I'll give it a try, but I'm unsure that it would be the best option.

**Comment by radare** [comment]
r2pipe is not replacing anything, is just an interface to interact with the r2 shell from other programming languages.

**Comment by botherder** [comment]
I get that, but why interact with the r2 shell instead of just using the shell?
I guess we could do that if we want r2 output to be returned through the API or Web interface. In that case it would be nice if r2pipe bindings could be made available on PyPI.

**Comment by radare** [comment]
the webinterface uses r2pipe in javascript/jax. using the API with ffi is way slower than using fork+pipe+json parsing.

To use r2pipe just copy the .py file in your project. i dont know how the python packaging works to be able to upload it to the python repositories. it's already available for nodejs in native and pipe forms.

also, most commands can display the output in json, so you get native python objects if using r2p.cmdj() instead of .cmd()

**Comment by botherder** [comment]
I noticed you guys added r2pipe to PyPi. That's great, I'll work on better integration from 1.3.

**Comment by radare** [comment]
yep :) r2pipe is the easiest way to interact with r2, i plan to push a new update to the python repository to support w32 lang pipes, with r2pipe you just need to know the r2 commands to do what you need, which are probably going to change less than the API, and it requires no special compilation.

let me know if you have any question or problem related to this.

**Comment by botherder** [comment]
We're using r2pipe now, closing this ticket.
