### ISSUE TITLE
Mark sample stored or not stored in shell

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#274]
It would be useful to differentiate an open file when it is stored or not stored in the shell prompt. It could be something as easy as using a different color or adding a particular mark.

**Comment by deralexxx** [comment]
maybe we could use the terminology used by vim:

```
vi asd
"asd" [New File]
```
So we would only have to append [New File] to an unsaved session.
(Colors might be nice but think about color blind people

**Comment by botherder** [comment]
Good point.

**Comment by deralexxx** [comment]
So I had a short look at it, but I was unable to find the right place to start at.

**Comment by botherder** [comment]
I will take care of this.
