### ISSUE TITLE
Integration with MISP (Malware Information Sharing Platform) - features

### ISSUE THREAD

**Issue by elhoim** [viper-framework/viper#276]
Integrate with the Viper binary analysis framework (https://github.com/botherder/viper / http://viper.li/).
Integration areas I am thinking about (wild wish list):
- import sample from Viper to MISP
- export sample from MISP to Viper
- lookup samples hashes (MD5/SHA1/SHA256) from MISP into Viper
- lookup samples hashes (MD5/SHA1/SHA256) from Viper into MISP
- save output of analysis from a Viper binary into MISP attributes
- use yara rules from MISP in Viper

Reference for related MISP ticket: https://github.com/MISP/MISP/issues/456

**Comment by botherder** [comment]
I think it would be great.

**Comment by jahrome** [comment]
Absolutely, it is a feature I will look forward in the near future.

**Comment by nefutpowers** [comment]
+1 on this item, definitely looking forward to it

**Comment by dewiestr** [comment]
+1, this would be very useful

**Comment by botherder** [comment]
So, plans for implementation? Do we need to coordinate something with MISP people?

**Comment by kevthehermit** [comment]
I am famkliar with MISP will have a look this weeeknd.

**Comment by Rafiot** [comment]
Any news? @kevthehermit? I'm going to have a look this week.

**Comment by Rafiot** [comment]
FYI, I'm working on it, preliminary upload module will be available tomorrow

**Comment by Rafiot** [comment]
Initial version available, only with upload for now.

Todolist :
* Download (all samples from event, one sample on the system)
* Query of IOCs (hashes, domains, mutexes ....)
* Update events to add IOCs 

Any other ideas?

**Comment by elhoim** [comment]
Support multiple MISP instances

**Comment by Rafiot** [comment]
Not sure to understand: it is already possible pass the URL/key as parameter to the module.

If you want to be able to lookup in many instances at once and do it often enough that is gets annoying, I would recommend to setup a personal MISP instance to sync them all.

**Comment by Rafiot** [comment]
Sample download implemented (MD5 and EventID) -> f0c4f1335119e76732980df5514293ae56b232b1

**Comment by elhoim** [comment]
Very nice, thanks you!

**Comment by kevthehermit** [comment]
Getting errors. 

```
viper 0ee942ae726add42603b29900144130c36ad3187ec7ab200b922307ed007603f > misp upload -e 1 -d 3 -t 0 -a 1
[!] The command misp raised an exception:
Traceback (most recent call last):
  File "/root/github/viper/viper/core/ui/console.py", line 259, in start
    module.run()
  File "/root/github/viper/modules/misp.py", line 158, in run
    self.upload()
  File "/root/github/viper/modules/misp.py", line 109, in upload
    self.args.info, self.args.analysis, self.args.threat)
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 191, in upload_sample
    info, analysis, threat_level_id)
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 171, in prepare_attribute
    raise NewAttributeError('{} is invalid, category has to be in {}'.format(analysis, (', '.join(['Payload delivery', 'Artifacts dropped', 'Payload Installation', 'External Analysis']))))
NewAttributeError: 1 is invalid, category has to be in Payload delivery, Artifacts dropped, Payload Installation, External Analysis
viper 0ee942ae726add42603b29900144130c36ad3187ec7ab200b922307ed007603f >

```

**Comment by kevthehermit** [comment]
Also

```
viper > misp download --hash 595c235c600d374d9fe17c281cf5143a
[!] Not Found
viper >

```

**Comment by Rafiot** [comment]
Just to be sure we are on the same page: 
* Are you using this branch: https://github.com/viper-framework/viper/pull/311
* download will only be able to download the sample if it is already on MISP (is it the case?)

The second error is weird, I'll check again tomorrow morning.

**Comment by kevthehermit** [comment]
OK used #311 

Search and upload are fine without error. Download still seems to get upset tried 3 differnent hashes always the same error no matter what hash i specify

```
viper alien_1.jar > misp search -q 141524e816a68793ad248cf88f65420c
[+] Found the following events:
[+] 	http://misp.malwareconfig.com/events/view/2
viper alien_1.jar > misp download --hash 141524e816a68793ad248cf88f65420c
[!] The command misp raised an exception:
Traceback (most recent call last):
  File "/opt/viper/viper/core/ui/console.py", line 259, in start
    module.run()
  File "/opt/viper/modules/misp.py", line 161, in run
    self.download()
  File "/opt/viper/modules/misp.py", line 84, in download
    ok, data = self.misp.download_samples(sample_hash=self.args.hash)
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 323, in download_samples
    unzipped = StringIO.StringIO(archive.open(f['md5'], pwd='infected').read())
  File "/usr/lib/python2.7/zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named u'595c235c600d374d9fe17c281cf5143a' in the archive"
viper alien_1.jar > misp download --hash 595c235c600d374d9fe17c281cf5143a
[!] The command misp raised an exception:
Traceback (most recent call last):
  File "/opt/viper/viper/core/ui/console.py", line 259, in start
    module.run()
  File "/opt/viper/modules/misp.py", line 161, in run
    self.download()
  File "/opt/viper/modules/misp.py", line 84, in download
    ok, data = self.misp.download_samples(sample_hash=self.args.hash)
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 323, in download_samples
    unzipped = StringIO.StringIO(archive.open(f['md5'], pwd='infected').read())
  File "/usr/lib/python2.7/zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named u'595c235c600d374d9fe17c281cf5143a' in the archive"
viper alien_1.jar > misp download --hash be4938b075c186cce420445219edad65
[!] The command misp raised an exception:
Traceback (most recent call last):
  File "/opt/viper/viper/core/ui/console.py", line 259, in start
    module.run()
  File "/opt/viper/modules/misp.py", line 161, in run
    self.download()
  File "/opt/viper/modules/misp.py", line 84, in download
    ok, data = self.misp.download_samples(sample_hash=self.args.hash)
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 323, in download_samples
    unzipped = StringIO.StringIO(archive.open(f['md5'], pwd='infected').read())
  File "/usr/lib/python2.7/zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named u'595c235c600d374d9fe17c281cf5143a' in the archive"
viper alien_1.jar > 


```

![misp_download](https://cloud.githubusercontent.com/assets/2545096/9437379/eaa0ae74-4a4d-11e5-839d-2d7464f687e4.png)

**Comment by Rafiot** [comment]
Yep, working on it: the zipped file now contains the file with its original file name (instead of the md5). I'm going to release pymisp 1.7 in a couple of minutes to support that.

Downloading by hash has an other problem that will need to be fixed server side: it always returns all the samples... (see: https://github.com/MISP/MISP/issues/610)

**Comment by kevthehermit** [comment]
Nice work. :)

Will wait for the MISP/MSIP#610 to be resolved then test again and merge.

**Comment by Rafiot** [comment]
MISP/MSIP#610 is fixed :)
