### ISSUE TITLE
Long file name "breaks" the look of index page

### ISSUE THREAD

**Issue by GelosSnake** [viper-framework/viper#277]
When a long file name is present the index table gets unbalanced. 
![screen shot 2015-04-14 at 6 43 14 pm](https://cloud.githubusercontent.com/assets/5004714/7140833/4f63dea6-e2d6-11e4-94ab-dee49501c459.png)

Not a huge deal but might be worth looking at.

**Comment by botherder** [comment]
A word-wrap will do the trick.

**Comment by SnakeByteIL** [comment]
Thanks @botherder

**Comment by kevthehermit** [comment]
Will update this weekend

--
*Pinky*: "Gee, Brain, what do you want to do tonight?"
*The Brain*: "The same thing we do every night, Pinky—try to take over the
world!"

My Blog <https://techanarchy.net> | My GitHub
<https://github.com/kevthehermit> | My Public Key
<https://keybase.io/TheHermit> | My Linkedin
<https://www.linkedin.com/in/kevbreen>

**Comment by SnakeByteIL** [comment]
@kevthehermit do you want me to have a go at this?
