### ISSUE TITLE
error store  unicode characters in notes

### ISSUE THREAD

**Issue by mytts** [viper-framework/viper#290]
error store  unicode characters in notes

**Comment by deralexxx** [comment]
can confirm the issue, appears to be in that line:

```
title = raw_input("Enter a title for the new note: ")
```
in https://github.com/botherder/viper/blob/master/viper/core/ui/commands.py

**Comment by deralexxx** [comment]
see my proposal, not sure if is a nice solution

**Comment by deralexxx** [comment]
I have added it to https://github.com/botherder/viper/pull/294 as it is a more general problem.

**Comment by Rafiot** [comment]
Fixed.
