### ISSUE TITLE
Logging issue with new log command

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#299]
Now that we're piping the output of the commands to be able to use it in other interfaces, it becomes unintuitive for the command line. For example, when using the `store` command to import a large number of files, the log entry saying "file X stored" will only be shown when the command is completed, effectively losing visibility into the progress of the command as it runs.

**Comment by botherder** [comment]
I'm still quite unhappy about the current logging system and I feel it needs to be completely refactored. It feels clunky and the logging order doesn't make a whole lot of sense. For example, when we have raw_input() calls, nothing that should be printed before actually is clearly. Similarly, we don't get any sense of progression.
@kevthehermit @Rafiot and others, thoughts?

**Comment by kevthehermit** [comment]
Have a solution that keeps the logging format so the web etc will still work and you get live printing in the console

Just running some final tests then will send a pull.

**Comment by Rafiot** [comment]
Yes, we should have an immediate output for the logging (for example the mass download of samples from VT is very confusing).

@kevthehermit: if you have some code to do that, I'll definitely try out.

**Comment by kevthehermit** [comment]
Pull is here https://github.com/viper-framework/viper/pull/389

**Comment by botherder** [comment]
Closing.
