### ISSUE TITLE
Create Docker image

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#301]
Docker is increasingly being use for software deployment within the open source security community too. We should have a docker image which is up-to-date with latest developments.

**Comment by dewiestr** [comment]
Remark: Lenny Zeltser already created a remnux/viper docker image: https://github.com/REMnux/docker/tree/master/viper <https://github.com/REMnux/docker/tree/master/viper>

**Comment by botherder** [comment]
I have seen that, but it's too specific for REMNux I'm afraid. The install scripts make specific changes in the code to fix some hardcoded paths that are valid for REMNux only, I think.

**Comment by kevthehermit** [comment]
@botherder Do you want the DockerFile in its own repo under viper-framework

**Comment by kevthehermit** [comment]
https://github.com/viper-framework/viper-docker
