### ISSUE TITLE
Refactor with system-level installation and users repositories

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#302]
Instead of a self-contained folder, I've been considering restructuring Viper so that it can be provided with an installation script (probably Python setuptools), so that the main executable scripts are dropped in `/usr/bin/` and the rest is stored for example in `/usr/share/viper/` while the binaries and projects are instead stored for example in `$HOME/.viper/`.

I would like some feedback before proceeding with such a radical change.

**Comment by deralexxx** [comment]
So storing binaries and projects in home dir is good also for backup purposes.

I wonder how users then can use their own scripts (e.g. new/custom modules)

It would also be very nice to include and consider to provide a service for api.py and web.py (if that is a seperate point we can make it an issue as well).

In the end every decrease of barrier to get hands on viper is worth to spend time.

Maybe for 2.0?

**Comment by kevthehermit** [comment]
I like the idea. While refactoring it might be worth looking at providing
full SQL Support. Projects is the major hurdle here.
--
*Pinky*: "Gee, Brain, what do you want to do tonight?"
*The Brain*: "The same thing we do every night, Pinky—try to take over the
world!"

My Blog <https://techanarchy.net> | My GitHub
<https://github.com/kevthehermit> | My Public Key
<https://keybase.io/TheHermit> | My Linkedin
<https://www.linkedin.com/in/kevbreen>

**Comment by botherder** [comment]
Can you elaborate on what you mean with "full SQL support"?

**Comment by kevthehermit** [comment]
Allow for MySQL or PostgreSQL. I manually change the connection string on my instance but it doesn't support projects.
