### ISSUE TITLE
Feature: Replace SQLlite DB with MongoDB

### ISSUE THREAD

**Issue by theevilbit** [viper-framework/viper#313]
I think long term MongoDB would be much more robust, and would allow greater flexibility.

**Comment by Rafiot** [comment]
I don't think it is a good idea, as it would require the users to install and configure mongodb.

**Comment by frennkie** [comment]
I would also tend to reject this suggestion. SQLAlchemy is very robust and flexibel. If a different backed would be required then SQLAlchemy could be configured to use a 'real' database (e.g. Postgres, Maria/MySQL). But as @Rafiot states.. that would be an additional software and service requirement.
