### ISSUE TITLE
Feature: Store module results in DB and make it searchable

### ISSUE THREAD

**Issue by theevilbit** [viper-framework/viper#314]
It would be great to store all the module results automatically in the DB, and make it searchable.

**Comment by deralexxx** [comment]
Reasonable feature request indeed, hard to realize I guess.

Nothing we can do adhoc.

**Comment by kevthehermit** [comment]
We can store the ouptut in  a note. and use the command as the note title. This would make it searchable

**Comment by deralexxx** [comment]
hm that is indeed a nice idea, but what if we decide to change that in the future? I would introduce it as a new table (with the same structure as note)

**Comment by kevthehermit** [comment]
https://asciinema.org/a/26534 Showing Module output being stored in the database

**Comment by theevilbit** [comment]
Nice! :) Thanks!
