### ISSUE TITLE
Parent Child Relationship

### ISSUE THREAD

**Issue by JuTz0r** [viper-framework/viper#315]
We use viper a lot to store malware from our incidents, one thing that we have as a wishlist is the ability to have the malware in a Parent - Child relationship.

Example:
bad_file.doc
          |_ evil_malware.exe

This way we could have a bit more information about that particular .exe and where it came from and see it visually if need be.  I would love to have this kind of feature if you guys think it's worthwhile.

**Comment by ynvb** [comment]
+1
This is my *most desired* feature as well.

**Comment by deralexxx** [comment]
yes that makes sense, and maybe we can combine that with fuzzy, so that you can browse using fuzzy results

**Comment by egberts** [comment]
Wut?  I couldn't find the commit for this feature. Where do I find this commit ID?
