### ISSUE TITLE
Using MISP as a remote storage for indicators

### ISSUE THREAD

**Issue by Rafiot** [viper-framework/viper#325]
It would be great to be able to feed IOCs into a remote MISP instance directly from Viper. 
Right now, you can already upload samples to MISP but it would be cool to be able to do more:
* hashes only
* mutexes, strings, regkeys...
* network indicators (domain, urls, ips, ...) 
* any kind of comments
* Tags

And possibly some stuff.

But to do that, we will need to store some information (event ID, default distribution level...). What do you think of using the session to store that? I didn't really dig into in but do you think it would be possible and/or a good idea?

**Comment by kevthehermit** [comment]
Im looking at ways to storre module output in to the DB. This could allow for this level of interaction

**Comment by deralexxx** [comment]
hm do you want to pull information from misp to viper and store it in viper or upload results of an investigation from viper to misp?

**Comment by Rafiot** [comment]
Viper -> MISP, the idea is to push information to a remote MISP instance while you do the analysis. 

My working branch is here: https://github.com/Rafiot/viper/tree/mispadvanced

**Comment by kevthehermit** [comment]
Was playing with pushing attributes but having issues https://github.com/CIRCL/PyMISP/issues/18

**Comment by Rafiot** [comment]
Yep, totally untested code, working on it :)

**Comment by Rafiot** [comment]
Merged, closing this issue.
