### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Rafiot** [viper-framework/viper#327]
I've been looking around to get viper to work on python 3, this is the current status for reference.

(the following remarks only apply of we don't care about anything below 2.7)

**External dependencies**
- pefile: pip version requires python 2, this one is compatible: https://github.com/esnesenon/pefile
- oletools: requires python2, no known python 3 version

**Core**

Cosmetic changes, nothing noticeable, I may just propose a pull requests later today.

**Modules**

Might be a little bit more touchy and need some more work on some of the modules, but the vast majority is already compatible.

**Comment by botherder** [comment]
Question is, is there a good reason to make that effort yet?

**Comment by Rafiot** [comment]
Porting core will have to be done at some point, doing it now cannot hurt.

For the rest, I leave it for reference when we will do the switch, I don't think it is worth the effort to do it right now.

**Comment by decalage2** [comment]
FYI I tried to port oletools to Py3 using tools such as 2to3, but there is complex parsing code (e.g. olevba) which will require a lot of manual rewrite. So oletools will only support Python 2 for now.

**Comment by Rafiot** [comment]
@decalage2 good to know, thank you.

**Comment by Rafiot** [comment]
Ongoing work: https://github.com/viper-framework/viper/pull/495

**Comment by Rafiot** [comment]
Merged!
