### ISSUE TITLE
Web server not loading correctly

### ISSUE THREAD

**Issue by wirehack7** [viper-framework/viper#334]
bfdfaa943d7a61e1972a02a134cc3c590242893d seems to have broken some things. @botherder tried to fix it (5798b423ae8fd0912062733de112fa5f326d751f), but it only loads the HTML now. Styles are broken.

It affects `web.py`

**Comment by wirehack7** [comment]
Workaround until it got fixed: 
Reverting to 0b01efad9b00cc26685d03c65c9a4832a3a70a5c

**Comment by botherder** [comment]
@Enchantertim care to look into what happened?

**Comment by Enchantertim** [comment]
Will do so, but im kind of swamped with work today and tomorrow.

Ive taken a look at the source, but as far as I can see, the adjustment(s) should be minor.

**Comment by kevthehermit** [comment]
Easy fix - 
Line 41 ish app = application = bottle.default_app()

**Comment by wirehack7** [comment]
That worked @kevthehermit 
Changed the line, styles are correct again.
cc: @botherder
