### ISSUE TITLE
7z support for upload

### ISSUE THREAD

**Issue by wirehack7** [viper-framework/viper#342]
Hello,
It will be great if 7z files can also be uploaded and extracted by Viper.

Thanks in advance.

**Comment by kevthehermit** [comment]
Will have a look at adding support, In the mean time you can use ! to run os commands and chain them together with ;

e.g. viper>  ! 7z e $self -o /tmp/blah ; store -f /tmp/blah

**Comment by wirehack7** [comment]
Thank you @kevthehermit 
But I need it also for web access (upload). I am looking forward for the enhancement.

**Comment by JuTz0r** [comment]
I have my whole group at work using Viper and one workflow process I created was to have a SAMBA share powered by python and bash script.  The bash script runs the python script every 2 seconds while the python script will either Unzip a file (with or without pw of Infected), extract the file from a .bup , and takes a file from ECAT and renames it and submits it to VIper via the API.  Naturally, if the file exists already Viper will send an error code 500 to which we rename the file "Duplicate-<md5hash>".

It has been working out pretty good so far and if you're in a large group its a decent way to handle malware safely.

**Comment by wirehack7** [comment]
Yes, but this is just a workaround, I want 7z support by Viper if possible so users can simple upload a 7z file with the same upload form they are using to upload other files to.

**Comment by shibumi** [comment]
Hello,
I would also enchourage this new feature. I am currently saving all my malware in 7z with this pattern:

(IP of malicious Host).7z 

my 7z contain files like whois report, screenshots etc.. it would be nice if viper could recognize what is a binary and would not import the information files (whois, screenshots) and some other stuff. 

even better would be an own place in the database for such 'additional information'-files.
I would also suggest to tag this files with the name of the 7z so we would have a link between the malware and the additional informations..

thx for your effort 

chris

**Comment by kevthehermit** [comment]
Tagging the name of the parent Zip is a nice idea, I can add that across all the compression methods.
 
I dont want to tell viper to ignore files, as they might not be important for you but may be for others. And Viper is not just for binary files.

**Comment by deralexxx** [comment]
I think the parent idea applies not only to zip / 7z etc. but also pdf that drop files, so this should be a rather big change, let's move that to a separate issue maybe

**Comment by kevthehermit** [comment]
This will probably wait till 1.4 When we commission the new Django App. After 1.3 is released i will do this and other feature requests.

**Comment by shibumi** [comment]
Why has been this closed? implemented?

**Comment by botherder** [comment]
I believe it has, yes.
![1529336355_1739_18 06 2018_1920x1080](https://user-images.githubusercontent.com/1032671/41546711-ac85daa4-731e-11e8-9a1f-e59735e3d1f5.png)

**Comment by shibumi** [comment]
cool thx!
