### ISSUE TITLE
Delete Projects ? Or modify Names 

### ISSUE THREAD

**Issue by priyalviroja** [viper-framework/viper#345]
Hii, 

I don't find a HTTP/API way to delete projects. Workaround would be play with database but people don't wanna mess up with database right ??

So It will be nice if we'll have add/update/delete functionalities wherever necessary.

Thanks.

**Comment by deralexxx** [comment]
Yeah this is indeed an issue, but is already covered in:
https://github.com/viper-framework/viper/issues/107
