### ISSUE TITLE
Feature: Queue Modules and Results. 

### ISSUE THREAD

**Issue by priyalviroja** [viper-framework/viper#346]
**Hiii,**

**It will be nice if we can run a queue of modules on a specific file. And final report consisting results from all modules.**

**If any module fails, skip that and move to next...** 

++ It will be great if we can download/print reports(in pdf format ?). 

**PS:** running one module on a specific file, wait for a result and keep repeating the same for other modules is bit frustrating. 

**Thanks.**

**Comment by kevthehermit** [comment]
Queuing Modules is on my list, First i want to store module output in the DB.

**Comment by priyalviroja** [comment]
Thanks. I look forward to the same.

**Comment by kevthehermit** [comment]
Demo for what i have so far.

https://asciinema.org/a/2mz5froyko10k99uyxjy7aoov

Uses a config file to set a series of commands that are then stored in the database for review

**Comment by priyalviroja** [comment]
Cool. This looks promising. :)
