### ISSUE TITLE
Display problem using radare2 within the viper

### ISSUE THREAD

**Issue by Maijin** [viper-framework/viper#354]
I'm encountering a display issue using @radare within the viper. The visual mode isn't responsive, and when quitting it's doing weird stuff see this asciinema: http://radare.tv/a/103

**Comment by botherder** [comment]
We need to refactor that module using r2pipe. Perhaps that will solve the issue.

**Comment by Maijin** [comment]
Hum the problem is I don't think the r2pipe is a good idea for Visual Mode since normally it is disabled.
Although the r2pipe need a module, that is clear :p
