### ISSUE TITLE
Office Module pareses output as List

### ISSUE THREAD

**Issue by JuTz0r** [viper-framework/viper#357]
As a recent pull, I noticed that the office module parses some entries out as a list:

Example:
['S', 'U', 'M', 'M', 'A', 'R', 'Y', '_', 'A', 'T', 'T', 'R', 'I', 'B', 'S'] Metadata
template	['N', 'o', 'r', 'm', 'a', 'l', '.', 'd', 'o', 't']

**Comment by kevthehermit** [comment]
Will have a look

**Comment by kevthehermit** [comment]
This was broken in the Python 3 compatibility uplift - https://github.com/viper-framework/viper/commit/784633ce688e48578acb15987c31a8819f82ceaf

Am updating the whole office module now, will fix this and improve the VBA parser

**Comment by kevthehermit** [comment]
Should be fixed now. Thanks, any more issues please re open
