### ISSUE TITLE
Pip package of m2crypto broken

### ISSUE THREAD

**Issue by Rafiot** [viper-framework/viper#362]
```
pip install m2crypto 
```

fails with

```
SWIG/_m2crypto_wrap.c:3537:18: fatal error: _lib.h: No such file or directory
```

Related corresponding issue on the main repo : https://gitlab.com/m2crypto/m2crypto/issues/60

Until a new PIP package is released, you can install m2crypto with: 

```
pip install git+https://gitlab.com/m2crypto/m2crypto.git
```

**Comment by botherder** [comment]
Is it fixed now? Cause I still can't install it:

```SWIG/_evp.i:12: Error: Unable to find 'openssl/opensslconf.h'

SWIG/_ec.i:7: Error: Unable to find 'openssl/opensslconf.h'```

Although both swig and libssl-dev are installed.

**Comment by kevthehermit** [comment]
looks like pip was updated 2015-10-19. I dont have a clean rig to test installing on

**Comment by Rafiot** [comment]
Oh, yeah, I have a dirty fix here: https://github.com/viper-framework/viper/compare/master...Rafiot:perso

**Comment by botherder** [comment]
Fuck M2Crypto, seriously. Can't we switch to a better and more updated library?

**Comment by kevthehermit** [comment]
This looks like a nice crypto lib. 

https://cryptography.io/en/latest/

Will need to check what we are actually using M2 for and check for coresponding features

**Comment by botherder** [comment]
This is still broken and causing issues with pip install file. Can we sort something out?

**Comment by Rafiot** [comment]
WIP, please give a try. I have to say I have mostly no idea how this verification thing is working but as it doesn't explodes, I'm close to assume it mostly works (beside the counterSignature thing)

**Comment by botherder** [comment]
Merged. I'll keep the ticket open until we fully transitioned out of M2Crypto.

**Comment by Rafiot** [comment]
The lib isn't used anymore.
