### ISSUE TITLE
Debup module in web interface

### ISSUE THREAD

**Issue by Beercow** [viper-framework/viper#368]
Is there a way to extract the files, in the web interface, from a bup file? While the option is there to do it, there is a sloght problem. The web interface does not switch to the session or save the file. The only option that works properly is the info flag. Everythiing works form the command line. Would be nice if it worked from the web gui.

**Comment by kevthehermit** [comment]
you can use the command line entry box and chain commands together using ';'

Something like ```debup -s; store``` should work. Will test when i get a chance

**Comment by Beercow** [comment]
Thank you for the quick response. Keep forgetting tou can chane commands. Will test when I get a chance.

**Comment by Beercow** [comment]
Found a solution. open -l (n);debup -s;store.  Thank you
