### ISSUE TITLE
Feature request: In MISP module add VT commands

### ISSUE THREAD

**Issue by elhoim** [viper-framework/viper#374]
Add a vt_enrich_by_ip command to leverage the information stored in pages such as [this one](https://www.virustotal.com/en/ip-address/199.79.62.69/information/) (hostnames, hashes, URLs and links to VT analysis pages).

Add a vt_enrich_by_hostname command to leverage the information stored in pages such as [this one](https://www.virustotal.com/en/domain/dkoxqnnednme.biz/information/) (IPs, hashes, URLs and links to VT analysis pages).

**Comment by botherder** [comment]
Is this something for you, @Rafiot ?

**Comment by Rafiot** [comment]
Sure, I'll see how I can implement that :)

**Comment by Rafiot** [comment]
can you assign it to me, please, so I don't forget it... :)

**Comment by Rafiot** [comment]
I started to look at it, and I'm not sure we want to have something completely automatic wth misp: the passive DNS has a lot of things, and it will probably add plenty of unrelated attributes. It would be better to have something interactive.

I will have a look at how to implement it (is it is generic enough, it could be an option for the whole MISP module).

First of all, I'll add the pdns option to the VT module.

**Comment by Rafiot** [comment]
This PR allows you to query VT for DNS info: https://github.com/viper-framework/viper/pull/380

Automatic enrichment is possibly not the best idea at it will have plenty of false positive.

**Comment by Rafiot** [comment]
The better option is to use the MISP modules for that, it gives more granularity. 

I think we can close this issue.
