### ISSUE TITLE
[Idea] introducing schema version

### ISSUE THREAD

**Issue by deralexxx** [viper-framework/viper#377]
I struggled a bit with updating to the current version using the update script and it might be handy for people to see their current schema version as well as the to-be schema version.

Any Ideas?

**Comment by kevthehermit** [comment]
What was your issue? Makes sense to fix that. There is no point listing schema versions, as there is no way to stay on the old one and keep up to date with teh modules. Its either update all or none.

**Comment by deralexxx** [comment]
For some reason I uodates my database twice and my table colums got moved but the values stayed. Need to do some testing with different versions of viper to reproduce it.

Will create another issue to let the update script create the backup not with a fixed name but with a timestamp.

**Comment by deralexxx** [comment]
as I was unable to reproduce it, it is closed.
