### ISSUE TITLE
500 errors after latest upgrade

### ISSUE THREAD

**Issue by Beercow** [viper-framework/viper#378]
I've just upgraded viper and the databases to latest commit. In the web interface, I am receiving errors. If I switch projects, no matter which project I select after that gets stuck on the first project I opened. After clicking around I end up with a 500 error. See screen shots.

web log:
![viper error1](https://cloud.githubusercontent.com/assets/10360919/11407344/db53b2f4-9377-11e5-828c-1707e5bf45a3.png)

Web page:
![viper error 2](https://cloud.githubusercontent.com/assets/10360919/11407358/eaf55c94-9377-11e5-9a12-5beb4a6a961d.png)

**Comment by kevthehermit** [comment]
Will have a look tonight. Did you pull a new copy from git or use the update script.

**Comment by Beercow** [comment]
I used the update script. In order to get the update script to work, I had to change StringIO to BytesIO because it would throw an error. But that is a different issue. I don't think there is an issue with the data base files because if I restart the web.py, I can switch to a different project and all the files show up.

**Comment by Beercow** [comment]
It seems like the bottle server is mucking up the paths for some reason.

**Comment by kevthehermit** [comment]
Thanks will fix asap

**Comment by Beercow** [comment]
I see that you did come up with a fix that day. I will not be able to test until Monday. Will keep you informed on the outcome. Thank you.

**Comment by Beercow** [comment]
Web fix commit fixed the issue. Thank you.
