### ISSUE TITLE
Is the history file broken?

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#384]
I noticed that now the history file is created in the current folder of viper.py (at least if no project is specified). Originally it was intended to be created either in $HOME or in the project folder. Is this intended behavior?

**Comment by kevthehermit** [comment]
As part of the ability to specify a remote directory I included the history
file here so for example if you connect from 2 different machines you can
use the same dB files and history.

**Comment by kevthehermit** [comment]
Can chnage back if you prefer

**Comment by rayschippers** [comment]
This appears to have broken viper on OS X as well. Now if you have no history file Viper loads fine, if you have a history file you get a readline error. I've installed gnureadline as per http://ipython.org/ipython-doc/2/install/install.html#readline but it still dies with:

You have 0 files in your default repository
Traceback (most recent call last):
  File "viper.py", line 25, in <module>
    c.start()
  File "/Users/raymond/viper/viper/core/ui/console.py", line 138, in start
    readline.read_history_file(history_path)
IOError: [Errno 1] Operation not permitted
