### ISSUE TITLE
WebUI support for stored analysis

### ISSUE THREAD

**Issue by cvandeplas** [viper-framework/viper#396]
When we use the CLI of Viper the output of the commands is saved in the analysis table. 
However the WebUI does not do this.
Also it would be practical to see the analysis history in the WebUI.

**Comment by kevthehermit** [comment]
This is all in the new django app I'm working on :).

**Comment by cvandeplas** [comment]
oh, great, is that already available somewhere? I'm probably not yet looking in the right place.

**Comment by kevthehermit** [comment]
Not yet. I'm hoping to have the first push up next week.  Just testing and
fixing a few bugs before I do.

**Comment by cvandeplas** [comment]
okay, I'll keep an eye here.
