### ISSUE TITLE
Problem submitting sample to VT in Viper

### ISSUE THREAD

**Issue by aladejebi** [viper-framework/viper#398]
I kept getting this error message each time I try to submit a sample to VT. I did entered my private key as shown in the screen capture below.

![pic1](https://cloud.githubusercontent.com/assets/10053433/12208859/24d1cd98-b615-11e5-90ef-58b5cdfa3036.png)
![pic2](https://cloud.githubusercontent.com/assets/10053433/12208865/2b5ae92e-b615-11e5-90d4-e0f23ef64fa3.png)
![pic3](https://cloud.githubusercontent.com/assets/10053433/12208866/2dd2c5d2-b615-11e5-99cb-406831d2f5e7.png)

**Comment by kevthehermit** [comment]
You need to set either private OR Intel true not both

**Comment by aladejebi** [comment]
I did but the result is the same. 
virustotal]
virustotal_has_private_key = Truevirustotal_has_intel_key = Falsevirustotal_key ='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

See scren shot below:



Thanks,
israel.

**Comment by Rafiot** [comment]
Also, did you rename the config file from `viper.conf.samples` to `viper.conf`? It is the error message I see in your 3rd print screen.

**Comment by aladejebi** [comment]
I renamed it but I kept the viper.conf.samples in the same folder. Do you recommend i remove it leaving only viper.conf in the folder ?

**Comment by Rafiot** [comment]
No, as long as `viper.conf`is there, it's good.

Can you try from the command line, please? I'm not sure I can effectively debug the web interface.

**Comment by aladejebi** [comment]
I got the same message at the command line interface..See the screen capture below:
![pic 5](https://cloud.githubusercontent.com/assets/10053433/12215375/ce7f562a-b67f-11e5-8f2c-ccd58f0129d1.PNG)

**Comment by kevthehermit** [comment]
Tested with the current version

```
viper AGREEMENT1.png > virustotal -s
[*] VirusTotal message: The requested resource is not among the finished, queued or pending scans
[*] VirusTotal message: Scan request successfully queued, come back later for the report
viper AGREEMENT1.png > virustotal
```

**Comment by kevthehermit** [comment]
What kind of API key do you have, Free / Private / Intel?

**Comment by aladejebi** [comment]
I have a private key

**Comment by aladejebi** [comment]
I have a private API key

**Comment by aladejebi** [comment]
What url did you use to pull the latest version of viper ? I know this is silly but just wanted to be 100% certain we are using the same version.

**Comment by aladejebi** [comment]
I got it to work now, I simply re downloaded the another instance from the repo. and modified  the config file as recommended by Kevin. (I thought I had done that before but it's working now, Many thanks Kevin and co. for all the help.
