### ISSUE TITLE
Feature Request : extract attachments for further investigation

### ISSUE THREAD

**Issue by oxitech239** [viper-framework/viper#403]
Given the practicality of Vipre and the current feature set in place i was amazed. After uploading a .msg file to Vipre it was not possible to continue investigation on the PDF inside. This i think is a critical feature missing.

**Comment by kevthehermit** [comment]
Its not missing its there. 

The smtp function allows you to export any attachments. 

Demo - https://asciinema.org/a/9303  Look at about the 02:30 mark and you will see the commands

**Comment by deralexxx** [comment]
thx @kevthehermit, but maybe we should consider to add it to the documentation / module howto to make it more clear.

Makes sense?
