### ISSUE TITLE
VIPER_ROOT in system-level install and paths to viper/data

### ISSUE THREAD

**Issue by Yawney** [viper-framework/viper#412]
If Viper is installed in a system, the VIPER_ROOT variable isn't set correctly. Instead of `/usr/share/viper` it's set to `/usr/local/lib/python2.7/dist-packages/viper-1.3-py2.7.egg`.

It was installed using
```
$ make
# make install
```

Also the paths to viper/data aren't set correctly
For system-level install: `/usr/share/viper/yara`, `/usr/share/viper/peid` and `/usr/share/viper/web`
For normal install: `viper/data/yara`, `viper/data/peid`, `viper/data/web`

Which then causes problems with things like `os.path.join(VIPER_ROOT, 'data/peid/UserDB.TXT')`.
All the paths work with normal installation except for
`for folder in ['/usr/share/viper/yara', os.path.join(VIPER_ROOT, 'yara')]:` in viper/modules/yarascan.py.
I assume there should be
`for folder in ['/usr/share/viper/yara', os.path.join(VIPER_ROOT, 'data/yara')]:`.

**Comment by botherder** [comment]
The transition isn't fully completed, so you're right. We need to fix some of the paths. However, I would want it to work both on a system-wide installation as well as just launched locally from the folder.

**Comment by botherder** [comment]
Can someone do some testing?
Should be fixed now.

**Comment by Yawney** [comment]
YARA and PEiD rules are fixed both locally and system-wide. The rat command can't find it's modules in either case.

I can't test if misp module downloads YARA rules to correct directory...

**Comment by botherder** [comment]
You're right, the rat module is broken.
I can easily fix for local user, I'm not yet sure how to fix it for global install. Need to find a way to iterate the folder of modules when it is stored in the global python library. @kevthehermit care to look into it?

**Comment by botherder** [comment]
Actually, with latest commit, it seems to be working alright to now. Can you verify?

**Comment by Yawney** [comment]
Yes, it works.
