### ISSUE TITLE
pdns has been deprecated and replaced by dnssync

### ISSUE THREAD

**Issue by shibumi** [viper-framework/viper#415]
Hello,
I am maintaining the Arch Linux package for Viper.
I just want to inform you that pdns has been replaced by dnssync. 
What are your plans? Do you want to replace pdns with dnssync or should pdns stay?
It would be glad to know this because I am not a fan of deprecated packages in  repositories (I look also in direction to the new .deb package).

greetings

Chris

**Comment by Rafiot** [comment]
Hmmm... Why? Are you talking of this package? https://github.com/metagriffin/dnssync

the PDNS module in viper uses: https://github.com/CIRCL/PyPDNS to query a passive DNS instance which seems unrelated to dnssync.

**Comment by shibumi** [comment]
@Rafiot 

Look at the disclaimer here:

https://pypi.python.org/pypi/pdns

```
Important

2015/01/01: The pdns project has been deprecated and replaced by the dnssync project. Please use that instead.
```

Seems like this message/information is missing on their github page.

**Comment by shibumi** [comment]
ahh sorry @Rafiot  you are right. I have mixed that up because the name is nearly the same.. this issue is closed.
