### ISSUE TITLE
TLS per default for Viper.li

### ISSUE THREAD

**Issue by deralexxx** [viper-framework/viper#424]
Would be nice to have https://viper.li per default and validated certificates maybe Lets encrypt.

Not a high prio of course

Thx

**Comment by botherder** [comment]
I want to restructure the website, perhaps just setup some blog somewhere. I'll take care of that when it's relocated.

**Comment by deralexxx** [comment]
hm now https://viper.li redirects to cuckoo webpage, is that somehow a duplicate content issue or redirect?
