### ISSUE TITLE
Unable to pull files from VirusTotal

### ISSUE THREAD

**Issue by pmurgatroyd** [viper-framework/viper#425]
Hi, I'm new to Viper, so please excuse me if this is a noob question.. I have a private API key configured for VirusTotal, but when I click to add a file by hash in the web interface, I get this error message:

![image](https://cloud.githubusercontent.com/assets/11664711/13907066/aae3ec58-eedd-11e5-8933-0381822fa354.png)

The console shows this:

![image](https://cloud.githubusercontent.com/assets/11664711/13907076/e13fcc54-eedd-11e5-8d39-ff0e81ab3a97.png)

can anyone help?

thanks!

**Comment by plutec** [comment]
Verified, there are a lot of problems with virustotal module, also with virustotal web processing.

**Comment by Rafiot** [comment]
I updated the VT module but never tried the web interface. I'll try to have a look at some point, but no promises I can do it any time soon.
In the mean time, I recommend to use the CLI, this one works fine.

Sorry for the inconvenience.

**Comment by plutec** [comment]
This can be another issue, but are you tried @Rafiot download a file from VT with cli?
It must be something like that: virustotal -d hash_file 
But it fails with a estrange error

**Comment by Rafiot** [comment]
I see, the help is wrong, the current syntax to use is the following: 

`viper > virustotal --search <hash> -d`

**Comment by pmurgatroyd** [comment]
thanks both.. I'll see if the CLI works for me in the interim!

**Comment by botherder** [comment]
I'd suggest renaming `--search` to `--find` and agreed to the rest.

Regarding the web interface, it really needs to be nuked and redone in Django. I should find some time for it, but if someone wants give it a crack please go ahead. Beware, I would be quite demanding when merging that code.

**Comment by pmurgatroyd** [comment]
thanks.. the CLI works with the above syntax.. is there anyway to get viper to download a file from VirusTotal and store it as a new file/session?  It just seems to download the file and then wont let me store it..?

**Comment by pmurgatroyd** [comment]
thanks, the CLI works for now.. until someone with more knowledge than me wants to fix the web interface :)

**Comment by S2R2** [comment]
The pull request should fix the issue in  the web ui

**Comment by botherder** [comment]
Can anyone else test it?

**Comment by deralexxx** [comment]
will test it tmrw

**Comment by pmurgatroyd** [comment]
I tested it earlier too and it looks good.. thanks!

**Comment by deralexxx** [comment]
ok thx then we can close that issue
