### ISSUE TITLE
Unable to convert db to new schema

### ISSUE THREAD

**Issue by nosferatu87** [viper-framework/viper#429]
When trying to convert old viper.db to the new schema I get errors showing the tables have not been created in the new database. I have tried running Database() independently and loading the db with sqlalchemy. It shows that no tables are being created. The db is being created properly from the web interface though. That's as far as I got into trying to resolve the issue.

`sqlalchemy.exc.OperationalError:`` (OperationalError) no such table: note "INSERT INTO note VALUES

**Comment by deralexxx** [comment]
which version are you currently running and which version have you used before?

**Comment by nosferatu87** [comment]
I was running 1.2.

**Comment by botherder** [comment]
How did you attempt the conversion?

**Comment by Rafiot** [comment]
Should be fixed now.
