### ISSUE TITLE
Unable to fetch online sandbox reports

### ISSUE THREAD

**Issue by cyber-cyborg999** [viper-framework/viper#430]
Hi,

I have recently started using Viper. And i came across this issue despite of adding the username & password in the viper.conf. The reports for sandbox is not showing any results. it is giving this error.

![viper-issue](https://cloud.githubusercontent.com/assets/13641169/14233482/8d632d6e-f9e7-11e5-8f5e-38d7ae86d35c.JPG)

Please help me if i missed anything to configure.

**Comment by emdel** [comment]
Can you double check with the command line?
Run `viper-cli` and use the `reports` module.

**Comment by wirehack7** [comment]
Tested it, same error on viper-cli as on viper-web.

**Comment by deralexxx** [comment]
somehow related with: https://github.com/viper-framework/viper/issues/478 ?
