### ISSUE TITLE
[viper-api] file/add/ endpoint should return sha256 on success

### ISSUE THREAD

**Issue by Chiggins** [viper-framework/viper#435]
I think it would be pretty useful for the /file/add/ endpoint to return the sha256 hash of the file uploaded instead of just the "message": "added" like it currently does. That'd be pretty useful for people utilizing the API for their own works when submitting a file.

**Comment by deralexxx** [comment]
agree, or even the info that will be returned if you search for files (so including tags, md5 etc).

**Comment by Rafiot** [comment]
PR merged.
