### ISSUE TITLE
Suggestion for tables

### ISSUE THREAD

**Issue by r3comp1le** [viper-framework/viper#437]
Use bootstrap tables for main page table of samples.  Would allow for quick filtering (tags and file names).  A user then could easily output json or csv of findings.
https://github.com/wenzhixin/bootstrap-table

Example
http://issues.wenzhixin.net.cn/bootstrap-table/

**Comment by r3comp1le** [comment]
Showing all available samples (Currently only 110 uploaded into Viper)
![alt](http://i.imgur.com/EcJPuHn.png)

Filter on a certain tag
![alt](http://i.imgur.com/gU4BHo3.png)

**Comment by deralexxx** [comment]
not sure but I think we will move the web UI to Django anyway, but such a use case make sense of course

**Comment by r3comp1le** [comment]
thanks
