### ISSUE TITLE
viper-update does't work with global install

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#445]
viper-update was intended to update the local folder, but now with global install it isn't really working anymore. I'm not really sure there is a really good way to re-engineer this, I think we should probably nuke the utility and just instruct to rather just use git to pull and install.

Thoughts?

**Comment by Beercow** [comment]
If the utility is nuked, we still need the db update part of it.

**Comment by Rafiot** [comment]
For MISP, the default update method is git pull and if there is a DB change, it is automatically triggered at the first page load.
Would it be possible to do the update automatically when we run the client or the web interface?

**Comment by botherder** [comment]
This still needs some work. The viper-update is still not working.

**Comment by botherder** [comment]
This seems to be the most pressing element missing before being able to release 2.0.
Anyone willing to look into how to port Viper database migrations at launch so we can get rid of viper-update?

**Comment by botherder** [comment]
Closing this in favor of moving the discussion to #407.
