### ISSUE TITLE
Misp create event error 

### ISSUE THREAD

**Issue by MxResearch** [viper-framework/viper#464]
I am having running MISP server on ubuntu and viper framework running on remnux system. when I am creating event using misp module of viper I am getting following error: 
 File "/opt/remnux-viper/viper/core/ui/console.py", line 235, in start
    module.run()
  File "/opt/remnux-viper/modules/misp.py", line 773, in run
    self.misp = PyMISP(self.url, self.key, verify, 'json')
  File "build/bdist.linux-x86_64/egg/pymisp/api.py", line 138, in __init__
    self.categories = self.describe_types['result']['categories']
KeyError: 'result'
******************************************************************************************
can anyone help me out with this error ?
Note: In PYMisp\example\keys.py, MISP URL and auth are set per my MISP instance running. I also though that there can be permission isses so i changed my var\wwwMISP to chmod -R 777

**Comment by Rafiot** [comment]
I see you are using remnux, and I'm not sure which version of pymisp is installed. Please try to do the following:
`pip install -U pymisp`

(I guess as root)

**Comment by MxResearch** [comment]
As per your suggestion I updated my pymisp using command: pip install -U pymisp but still I am getting the same error.: 
[!] The command misp raised an exception:
Traceback (most recent call last):
  File "/opt/remnux-viper/viper/core/ui/console.py", line 235, in start
    module.run()
  File "/opt/remnux-viper/modules/misp.py", line 773, in run
    self.misp = PyMISP(self.url, self.key, verify, 'json')
  File "/usr/local/lib/python2.7/dist-packages/pymisp/api.py", line 138, in __init__
    self.categories = self.describe_types['result']['categories']
KeyError: 'result'

I am using Host only adapter in my virtual machine. navigating to opt/remnux-viper and running command ./viper.py
command 1: misp search 
command 2: misp misp create_event -d 0 -t 2 -a 0 -i 'test'
getting same above error.
I have also updated viper.conf misp_url and misp_key with my misp instance. Not understanding what is the exact issue?

**Comment by Rafiot** [comment]
Okay, which version of MISP are you using then? 

The error you get is because you receive an unexpected response from the server.

**Comment by MxResearch** [comment]
Using MISP version 2.4.9

**Comment by Rafiot** [comment]
Okay, that's why. Can you update to the most recent one (`v2.4.51`), please?

To do that, simply do git pull from the directory you installed MISP in.

**Comment by MxResearch** [comment]
Thank you so much for the help, After updating MISP to latest version everything is working fine now.

**Comment by Rafiot** [comment]
Excellent, glad it worked out.

**Comment by Rafiot** [comment]
@botherder feel free to close :)
