### ISSUE TITLE
Some Additional

### ISSUE THREAD

**Issue by b0cq** [viper-framework/viper#465]
Hello Friends
Please, add this functions:
- function for management project (list, delete, archive, user list, author of project, etc);
- add support for work with Cyrillic (like "договоро купли продажи");
- add authorization for work with viper.

Thanks for you big work!

**Comment by b0cq** [comment]
Please, add function for sort list of case's 
![screen shot 2016-09-26 at 1 23 44 pm](https://cloud.githubusercontent.com/assets/22348546/18831094/7b6c2d7e-83ec-11e6-9525-6efab38fea77.png)

**Comment by deralexxx** [comment]
I assume you are using that "cases" as tags?

**Comment by b0cq** [comment]
No, just add new project - it's all

**Comment by deralexxx** [comment]
ok thx, can you open separate issues for the feature requests to be able to track and set proper priorities to each request rather than a bunch of ideas? That would be awesome.

A

**Comment by Beercow** [comment]
As far as sorting the list properly, I have this fixed in a pull request. It has not been accepted yet. 
https://github.com/viper-framework/viper/pull/451

**Comment by Rafiot** [comment]
Merged now.
