### ISSUE TITLE
[viper-api] http status codes / responses incorrect?

### ISSUE THREAD

**Issue by 0cta** [viper-framework/viper#466]
Hey there,

the piece of code we're currently struggling with is the following:

``` python
@route('/file/delete/<file_hash>', method='GET')
def delete_file(file_hash):
    success = False
    key = ''
    if len(file_hash) == 32:
        key = 'md5'
    elif len(file_hash) == 64:
        key = 'sha256'
    else:
        response.code = 400
        return {'message': 'Invalid hash format (use md5 or sha256)'}

    db = Database()
    rows = db.find(key=key, value=file_hash)

    if not rows:
        response.code = 404
        return {'message': 'File not found in the database'}

    if rows:
        malware_id = rows[0].id
        path = get_sample_path(rows[0].sha256)
        if db.delete_file(malware_id):
            success = True
        else:
            response.code = 404
            return {'message': 'File not found in repository'}

    path = get_sample_path(rows[0].sha256)
    if not path:
        response.code = 404
        return {'message': 'File not found in file system'}
    else:
        success = os.remove(path)

    if success:
        return {'message': 'deleted'}
    else:
        response.code = 500
        return {'message': 'Unable to delete file'}
```

When deleting a file via REST interface, we face some strange behavior:
1. Requests always return a status code "200", even if they fail with respect to the api logic.
2. When deleting an existing file from the repository, the response object tells "Unable to delete file."
**The file is deleted though!**

We tried to substitute the `response.code = 404` by `response.status = 404` and solved the status code problem with this.

However, the last piece of code still produces the "Unable to delete file." problem and we haven't been able to solve this yet ... 

Greetings from Stuttgart,
0cta

**Comment by botherder** [comment]
Really bizarre. I will look into that.

**Comment by Lost4Now** [comment]
I submitted PR #500 to fix this issue.

**Comment by Rafiot** [comment]
Merged.
