### ISSUE TITLE
Adding an option to use a password for the exported zip archive

### ISSUE THREAD

**Issue by tykkz** [viper-framework/viper#474]
Hello there,

I need to set a password when exporting the current session to a zip file. 

I have searched a bit and found out that _ZipFile_ python module (which is [used to create extracted zip files](https://github.com/viper-framework/viper/blob/master/viper/core/ui/commands.py#L875)) does not support writing password protected zip files to the disk.

So; here we have two options:
1. Use the [pyminizip](https://github.com/smihica/pyminizip) library (may cause problems in different distros,)
2. Add 7z dependency to the project and follow the method described [here](https://stackoverflow.com/questions/2195747/python-code-to-create-a-password-encrypted-zip-file/2366917#2366917).

I think that we should add 7z dependecy and use it. Since there is a request in #342 for "7z support for upload", viper will probably be dependant on the 7z project.

Based on your inputs, I will update the code and submit a pull request.

**Comment by deralexxx** [comment]
hm yes, adding 7z is a good idea, both for input and output. So happy to see your PR.

A

**Comment by frennkie** [comment]
@tykkz @deralexxx Exporting to 7z with password is implemented (it requires that `p7zip-full` is installed on the system):

```
seven viper My.pdf > export -p -7 /tmp/
Password:
confirm Password:
[*] File archived and exported to /tmp/My.pdf.7z
```

**Comment by Rafiot** [comment]
Closing :)
