### ISSUE TITLE
Query regarding sending samples from remote machine to viper framework

### ISSUE THREAD

**Issue by MxResearch** [viper-framework/viper#475]
Hi,

Is there any way to send/import samples from remote system directly to viper. 
Currently we can import samples from local system by using store -f /path-to-import command.

I had shared samples from remote system using samba and then used store -f samba network path but viper gave error specified invalid folder. Is there any other way around to do that ?

**Comment by botherder** [comment]
You can use viper-api

**Comment by MxResearch** [comment]
Hi @botherder , 

Yes I am aware of viper-api, but I want to upload samples in bulk from remote system. Through viper-api we are able to upload individual file only.

**Comment by deralexxx** [comment]
@MxResearch viper-api is the right thing if you want to push something to viper, e.g. you have possibility to run a script on your remote system.

You could also hack a little script that SCPs your files from $Remote to $Local and then pushes the files to viper using viper-api

Other then that store -f /path should work as long as the path is mounted readable for the OS. Maybe you can provide your specific envirenment / OS / protocolls involved?

**Comment by deralexxx** [comment]
guess we can close this one.
