### ISSUE TITLE
malwr.com report will no longer work

### ISSUE THREAD

**Issue by dewiestr** [viper-framework/viper#478]
Hi guys,

I think the malwr.com part in the report module should be removed, seeing as you need to get past a captcha to login to the website now. Considering this, requests is not longer going to be able to build up a session.

Regards,

**Comment by deralexxx** [comment]
indeed, that is an issue. but before removing a module, maybe @botherder has insight on how to keep the module working.

Will tag it as bug confirmed.

**Comment by deralexxx** [comment]
so I would recommend to remove the module and re-activate it once malwr. is back.

**Comment by Rafiot** [comment]
Makes sense. Like adding `-on_hold` to the file name, so it isn't autoloaded?

**Comment by dewiestr** [comment]
Malwr.com is back up again... This can be closed I guess.

**Comment by Rafiot** [comment]
Thanks, closing then.
