### ISSUE TITLE
Custom config file

### ISSUE THREAD

**Issue by dewiestr** [viper-framework/viper#480]
I see that it isn't possible to give the cli a custom viper.conf file. Is that something worth implementing ? 

Also the Config Class, does not use the cfg - variable ( I already added a pull request for this: https://github.com/viper-framework/viper/pull/479 )

**Comment by deralexxx** [comment]
hm is that something that would be used? If so, yes should not be that hard

**Comment by Rafiot** [comment]
closing this issue, I will merge the PR asap
