### ISSUE TITLE
Viper-web and viper-api 1.3-dev appears to ignore viper.conf

### ISSUE THREAD

**Issue by DigiAngel** [viper-framework/viper#503]
Topic :)  Snippets from viper.conf:
~~~
[paths]
storage_path = /opt/viper/storage

[web]
enabled = True
host = 0.0.0.0
port = 7070

[api]
enabled = True
host = 0.0.0.0
port = 9090
~~~

Yet when starting viper-web it tries to create a projects directory (easily fixed with sym-linking storage/projects to /opt/viper/projects).  However the on viper-web start I see:
~~~
Bottle v0.12.9 server starting up (using WSGIRefServer())...
Listening on http://localhost:9090/
Hit Ctrl-C to quit.
~~~

and on viper-api I see:
~~~
Bottle v0.12.9 server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.
~~~

I know I can force the host/port, which I do, but I was curious why neither of these apps appear to read the viper.conf file.  Thank you

**Comment by botherder** [comment]
I wouldn't be surprised. At the moment I consider viper-web to be entirely broken and rather dead, and viper-api needs to be fixed up.

**Comment by DigiAngel** [comment]
Ah that's a drag ☹  I'm enjoying the web portion once I have access to
it.  Well please let me know if I can test anything out.

**Comment by frennkie** [comment]
@DigiAngel I picked up the work that has already been done on moving the API and Web Interface to Django.. If you are interested in testing and helping out: #433 (but please be aware that this is completely "work in progress" and far from a "beta").

**Comment by DigiAngel** [comment]
Yea I'm down...lemme git pull and see what I can do...thank you!

**Comment by cvandeplas** [comment]
I can confirm there is at least 1 user for viper-web :-)  
The user-friendlyness of uploading a file and running a module over a webinterface (no ssh nor file-copying) is a win for some of us. I'll keep an eye on #433 though.

I haven't had the issue with viper.conf not being loaded though. The conf is stored in `/etc/viper/viper.conf`.
