### ISSUE TITLE
bash-completion/Cisco-like CLI

### ISSUE THREAD

**Issue by egberts** [viper-framework/viper#515]
I often wonder if it is time to allow us to hit "TAB" key for auto-completion of keystrokes.

And that includes the dash options as well.  <<- emphasis

Perhaps, Python Fire module can help us out here.

https://github.com/google/python-fire

**Comment by deralexxx** [comment]
Hey @egberts, can you explain where you are missing auto complete?
At least for the commands it does work like you are requesting.

I type "he" press Tab and it completes to help in viper-cli

**Comment by frennkie** [comment]
Currently - as far as I see it - only the following is completed:
* commands names
* modules names
* file/path names

What's missing is the completion of the **options** of commands and modules, right @egberts ?
