### ISSUE TITLE
Python 2/3 issue with PyMISP module

### ISSUE THREAD

**Issue by Tux-Panik** [viper-framework/viper#521]
Hello,

I'm trying to troubleshoot a python version issue due to PyMISP module:

`user@host:/opt/remnux-viper# python2 viper-cli`
>/usr/local/lib/python2.7/dist-packages/pymisp/api.py:18: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
/usr/local/lib/python2.7/dist-packages/pymisp/mispevent.py:45: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
/usr/local/lib/python2.7/dist-packages/pymisp/api.py:36: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
(ASCII ART)
 >   
>You have 0 files in your default repository

`user@host:/opt/remnux-viper# python3 viper-cli`
>Traceback (most recent call last):
  File "viper-cli", line 7, in <module>
    from viper.core.ui import console
  File "/opt/remnux-viper/viper/core/ui/console.py", line 16, in <module>
    from viper.core.plugins import __modules__
  File "/opt/remnux-viper/viper/core/plugins.py", line 39, in <module>
    __modules__ = load_modules()
  File "/opt/remnux-viper/viper/core/plugins.py", line 24, in load_modules
    module = __import__(module_name, globals(), locals(), ['dummy'], -1)
ValueError: level must be >= 0

Same effects using user or root. Python 2.7 and 3.4 are installed.
**Is this issue telling you something?**
Thanks for you help,

Regards,
Julien

**Comment by Rafiot** [comment]
Yes, the master branch doesn't supports python3. You need to use the py3 branch in my repository: https://github.com/rafiot/viper/

If you find any bug, please let us know, the current status of the PR is there: https://github.com/viper-framework/viper/pull/495
