### ISSUE TITLE
Proxy implementation

### ISSUE THREAD

**Issue by Tux-Panik** [viper-framework/viper#522]
Hello,

Is there a way to use proxy through viper, especially to query public API  (Malwr, VT, etc.)?

I tried with "**http_proxy**" var and **/etc/hosts** cheat, but I doesn't work.
If you have any idea?
Thanks in advance,
Julien

**Comment by deralexxx** [comment]
Hey @Tux-Panik, all requests should respect your envirenment variables.

Can you explain how you use it? (Command line, API, Web....)

And check your http_proxy and https_proxy settings in envirenment?

Thx

**Comment by Tux-Panik** [comment]
Thanks @deralexxx for your answer.
I can't use "virustotal" module with command line.
See below some check and examples:

`user@host:~$ echo $http_proxy`
>http://{INTERNAL_PROXY_IP}:8080

`user@host:~$ echo $https_proxy`
>http://{INTERNAL_PROXY_IP}:8080

`root@host:~# echo $http_proxy`
>http://{INTERNAL_PROXY_IP}:8080

`root@host:~# echo $https_proxy`
>http://{INTERNAL_PROXY_IP}:8080

`user@host:~$ wget https://www.virustotal.com/`
>--2017-04-18 09:46:49--  https://www.virustotal.com/
Connecting to {INTERNAL_PROXY_IP}:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 22312 (22K) [text/html]
Saving to: ‘index.html’
100%[===============================================================================================================================================================>] 22,312      39.7KB/s   in 0.5s   
2017-04-18 09:46:50 (39.7 KB/s) - ‘index.html’ saved [22312/22312]

`user@host:~$ wget http://www.laredoute.fr`
>--2017-04-18 09:48:12--  http://www.laredoute.fr/
Connecting to {INTERNAL_PROXY_IP}:8080... connected.
Proxy request sent, awaiting response... 403 Forbidden
2017-04-18 09:48:13 ERROR 403: Forbidden.

Then, I launched viper framework, using sudo rights, and I loaded a file:

`viper supicisous_file.exe [not stored] > info`
>+----------+-------------------------------------------------------------------+
| Key      | Value                                                             |
+----------+-------------------------------------------------------------------+
| Name     | supicisous_file.exe                                               |
| MD5      | 07435c2f66d5fa60d5cd3fd0b9b1639e                                  |
+----------+-------------------------------------------------------------------+

`viper supicisous_file.exe [not stored] > misp search 07435c2f66d5fa60d5cd3fd0b9b1639e`
>[!] No matches.

`viper supicisous_file.exe [not stored] > virustotal`
>[!] HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /vtapi/v2/file/report?apikey={MY_IP_KEY}&resource=07435c2f66d5fa60d5cd3fd0b9b1639e (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f558121eb50>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

**Comment by Tux-Panik** [comment]
Hello,

I just tried with the same computer, unseting proxy variables, and with direct connection and it works.
I continue to troubleshoot this case.

`viper sshd > virustotal --search c3dc48655824e32c0463ff82cbd2aa2d`
>[\*] 0 out of 57 antivirus detected c3dc48655824e32c0463ff82cbd2aa2d as malicious.
>[\*] https://www.virustotal.com/file/03f9950607b107f0d05f10f3bc9927b37c936ed935d62abcab6a2461b075eefd/analysis/1492347953/

Thanks,
Regards

**Comment by deralexxx** [comment]
hm that is indeed a little odd, do you mind to take some wireshard traffic captures to verify that it is trying (or not) to connect to the proxy?

**Comment by Tux-Panik** [comment]
Hello,
I've tried another time today and capturing the traffic.
I also used vt-checker.py (https://github.com/Neo23x0/Loki/blob/master/tools/vt-checker.py) to compare traffic negotiation, because I know it works through the proxy.

There is no doubt:

- when I ran "vt-checker.py", my VM communicate only with the proxy. I don't see any DNS request and so one... only TCP and HTTP queries.

- when I ran "virustotal --search c3dc48655824e32c0463ff82cbd2aa2d", my VM obtains the Virustotal IP address using DNS queries and then, it tries to negotiate directly with this IP address (which it can't be reached without the proxy).

I'm not comfortable to provide publicly these two PCAP, due to security reasons. I can closely send them.
You'll find below two screenshots:

1) Capture made during "vt-checker.py" queries:

![vt-checker](https://cloud.githubusercontent.com/assets/22981167/25944479/c87e9886-3643-11e7-8dff-78e13ea8697a.png)

2) Capture made during "virustotal" query with viper-framework:

![viper](https://cloud.githubusercontent.com/assets/22981167/25944478/c87d42c4-3643-11e7-826c-c60cb2eb1b39.png)

Thanks for your help,
Regards,
Julien

**Comment by Rafiot** [comment]
There must be somewhere something that force-unset the variables. I'll have a look asap.

**Comment by frennkie** [comment]
Does #597 help for this issue?

**Comment by Tux-Panik** [comment]
Hello @frennkie , it seems your change fixes the issue. Many thanks for this.
I'm now able tor request VT (through a proxy) and MISP (without proxy).

However, I reach an error with PyMISP:

![image](https://user-images.githubusercontent.com/22981167/30419867-2bc194dc-9938-11e7-8504-d685297c3a6e.png)

- I use last Viper commit [471dba21c046d9782f5f2adb8680019327131844](https://github.com/viper-framework/viper/commit/471dba21c046d9782f5f2adb8680019327131844).
- I use last PyMISP commit [8573519adaf2f98593d866e4bd0f0a71b9f38e7d](https://github.com/CIRCL/PyMISP/commit/8573519adaf2f98593d866e4bd0f0a71b9f38e7d).

I read [this issue](https://github.com/viper-framework/viper/issues/276) , that could be linked, but I haven't any track to help.
May be I should open a different issue.
If you have any idea, thanks fo your help.
Kind regards,
Julien

**Comment by Rafiot** [comment]
@Tux-Panik that's probably my fault... looking at it

**Comment by Rafiot** [comment]
So it works for me, and using the heavily patched 2.4.80 release (not published).

This error means that the json export you receive is somehow invalid so there are few things you can give a try:
* use python 3.5, if it fixes is, I'd still like to investigate further
* print `a` line 448 (before it fails) to find out what is in there.

**Comment by Tux-Panik** [comment]
Hi,

* Using python 3.5 fixes it, but it raises another :-/

In fact, in this case I have a module issue:
![01](https://user-images.githubusercontent.com/22981167/30430873-ef765114-995c-11e7-8eaa-dbfaa6b3a74a.png)

If I try to solve it, downloading modules with "pip3", it triggers an exception:
![02](https://user-images.githubusercontent.com/22981167/30430911-15e6ffb0-995d-11e7-9c50-bf59911417c2.png)


As suggested, I'll close this issue "as solved" and I open a new one.
Kind regards,
Julien
* Printing "a" in line 448 of pymisp/mispevent.py provides the following:
![image](https://user-images.githubusercontent.com/22981167/30431213-2b3edb8e-995e-11e7-808a-e4b106c2a703.png)
