### ISSUE TITLE
add "about" command which displays some useful info

### ISSUE THREAD

**Issue by frennkie** [viper-framework/viper#523]
I think it would be nice to have an **about** (or some name like that) command in the Viper CLI.
Running this command would show some basic information like:
* the version of the running Viper CLI
* additional technical info (like DB path etc)
* some info about Viper (e.g. link to the homepage and the Github Repo - e.g. a hint where to open issues)

This could also be more elaborate and show which modules are available (and which are not due to missing dependencies).

**Comment by Rafiot** [comment]
yep, and maybe also display the logs
