### ISSUE TITLE
Uploading files to Different Project

### ISSUE THREAD

**Issue by uppusaikiran** [viper-framework/viper#537]
`curl -F file=@file_count.txt -F tags='foo,bar' -X POST http://192.168.150.113:2222/file/add
`
This command upload the files to default directory.But i want to upload file to different Project.I cant able to do that?

` curl -F file=@file_count.txt -F tags='foo,bar' project='Kiran' -X POST http://192.168.150.113:2222/file/add
curl: (6) Could not resolve host: project=Kiran
`

### Any suggestions on how to solve this?

**Comment by frennkie** [comment]
As far as I see it uploading to a different project is not implemented in the current API.
I have have rewritten the API in Django, but it's not complete and I don't know whether it will get merged sometime. 
But anyway, it would be great if you could do some testing.. :-D https://github.com/frennkie/viper/blob/django/README.md

**Comment by frennkie** [comment]
The syntax is different but it definitely supports upload to a different project. Check /api/v3/docs for the syntax.

**Comment by uppusaikiran** [comment]
[**@frennkie**](https://github.com/frennkie) commented on [Apr 22, 2017, 5:48 PM GMT+5:30](https://github.com/viper-framework/viper/issues/537#issuecomment-296369501 "2017-04-22T12:18:32Z - Replied by Github Reply Comments"):
> As far as I see it uploading to a different project is not implemented in the current API.  
> 
> I have have rewritten the API in Django, but it's not complete and I don't know whether it will get merged sometime.  
> 
> But anyway, it would be great if you could do some testing.. :-D [https://github.com/frennkie/viper/blob/django/README.md](https://github.com/frennkie/viper/blob/django/README.md)

Thanks @frennkie I will definitely look into it.
