### ISSUE TITLE
Scope of modules?

### ISSUE THREAD

**Issue by frennkie** [viper-framework/viper#538]
This is not really an issue... more a question: What is the scope of modules? 

The reason for asking is that it seems that almost all modules operate on a single file only. But there are exceptions. For example `yara scan -a` will scan **all files** in the current project (not in all projects). I haven't checked all modules, but I guess there are more modules that don't strictly operate on a single file, right?

The reason for asking this is that I'm thinking about adding the possibility to run modules to the Django Web API I'm working on (the current API already supports this). I would like the API to have a logical hierarchy also for the modules (e.g. `[..]/project/default/module/pe/` vs. `[..]/project/default/malware/sha256/module/pe/`)

**Comment by deralexxx** [comment]
what if you just turn it around?

/project/default/malware/module/pe/sha256

Where Sha256 is the param that tels to module what to take?

**Comment by frennkie** [comment]
While that's "theoretically" possible it doesn't quite fit with the Django Nested Router I'm using.. :-)  my endpoints currently look like this:

```
http://127.0.0.1:8080/api/v3/project/case123/
http://127.0.0.1:8080/api/v3/project/case123/malware/
http://127.0.0.1:8080/api/v3/project/case123/malware/988656aa9c57b4e135c35a3972db2716f19ae71419edb7b43d0617c1140ce8ce/
http://127.0.0.1:8080/api/v3/project/case123/malware/988656aa9c57b4e135c35a3972db2716f19ae71419edb7b43d0617c1140ce8ce/tag/
http://127.0.0.1:8080/api/v3/project/case123/malware/988656aa9c57b4e135c35a3972db2716f19ae71419edb7b43d0617c1140ce8ce/tag/23/
http://127.0.0.1:8080/api/v3/project/case123/malware/988656aa9c57b4e135c35a3972db2716f19ae71419edb7b43d0617c1140ce8ce/note/42/
```

I think I would go for this:

```
http://127.0.0.1:8080/api/v3/project/case123/malware/module/pe/  (as GET) - return (parsable) info about module
http://127.0.0.1:8080/api/v3/project/case123/malware/module/pe/  (as POST) - run module on one or more malware samples based on POST parameters (either list of <sha256> or even *all*)
http://127.0.0.1:8080/api/v3/project/case123/malware/module/pe/malware/<sha256>  (as GET) - run module on one malware sample
```
