### ISSUE TITLE
Unable to start viper-web

### ISSUE THREAD

**Issue by gra55h0pp3r** [viper-framework/viper#544]
I've installed VIPER and installed all the requirements using pip3 and when I run python3 viper-web -H 0.0.0.0 -p 9000 I get a lot of print statement errors. I see the code is still written for python 2.7, so all the print statements are missing the parentheses. When will this be fixed? Can I install VIPER as python 2.7 or do I have to wait for the merge tonight, then update my local instance?

  File "viper-web", line 409
    print new_file
                 ^
SyntaxError: Missing parentheses in call to 'print'

python3 viper-cli works just fine. One thing I noticed is you can't create projects by running projects -p NEWPROJECT

**Comment by Rafiot** [comment]
the current master branch doesn't support python3. The PR supporting python 3 will be merged tomorrow: https://github.com/viper-framework/viper/pull/495

Also, please note that the web interface is considered deprecated and there is an other bug rewrite ongoing: https://github.com/viper-framework/viper/pull/534

**Comment by gra55h0pp3r** [comment]
Okay. We were using the web interface to upload our malware samples, so that puts a monkey wrench into our operations. Is there any way I can revert to a certain branch that works in Python 2.7 for now; until the web interface is rewritten.

Thanks!

**Comment by gra55h0pp3r** [comment]
You can close this issue as I was able to resolved the issue. Ran into an issue where the html5lib was giving me an error when running the viper-web under py2, so I just had to update html5lib. 
pip install -U html5lib==1.0b8 (virtualenv python 2.7)
sudo -H pip install -U html5lib==1.0b8

**Comment by deralexxx** [comment]
thx @gra55h0pp3r will close it
