### ISSUE TITLE
Update viper.li

### ISSUE THREAD

**Issue by Rafiot** [viper-framework/viper#546]
viper.li doesn't seem to be updated automatically. @botherder do you mind doing it, or telling me how to do it?

**Comment by frennkie** [comment]
The Read The Docs build of the docs is failing due to pydeep -> libfuzzy.h iusses: http://readthedocs.org/projects/viper-framework/builds/5292030/ 

I assume that's the reason why http://viper-framework.readthedocs.io/en/latest/ is showing old data...

**Comment by Rafiot** [comment]
@botherder I added `docs/requirements.txt`. If you set it as requirement file to use in readthedocs, it will work again: https://readthedocs.org/dashboard/viper-framework/advanced/

Or you add me as collaborator on read the docs and I do it myself.

**Comment by frennkie** [comment]
@botherder It would be great if you could look into this so that the documentation can be updated! :-)

**Comment by alexandreborges** [comment]
@frennkie  Good afternoon. Please, remember that I made this suggestion about libfuzzy.h few days ago: https://github.com/viper-framework/viper/issues/542. Probably, @Rafiot has already made the change. :)

I hope you have a nice day.

**Comment by frennkie** [comment]
Yes.. change is already made (https://github.com/viper-framework/viper/blob/master/docs/source/installation/index.rst) and merged into master.. so as soon as the automatic build works again the docs will be update to date and contain the correct info.
@alexandreborges Please take note that as of this week you really **really** should run Viper with Python3.

**Comment by alexandreborges** [comment]
Thank you so much, @frennkie. I'll do it and I'll notify other people too. :)

**Comment by frennkie** [comment]
@botherder would you be so kind to help us out here and update the docs? Would be really good to have them updated! 

As Rafiot already wrote you really only need to make a little change on the readthedocs settings page.

**Comment by frennkie** [comment]
@botherder any chance you could have a look at this? 

This is now pretty dated and would be great if we could get the automatic doc build process running again: https://viper-framework.readthedocs.io/en/latest/installation/index.html

**Comment by botherder** [comment]
This is now fixed.
The documentation is updated, and https://viper.li points directly to it for convenience.
