### ISSUE TITLE
Move session into project

### ISSUE THREAD

**Issue by rommelfs** [viper-framework/viper#57]
Feature request: 

It would be great to move the current session into a specific project in order to keep things organized.

**Comment by adricnet** [comment]
For this, would it makes sense to have users *store* session to a new/named project? This is how we are thinking about using viper for some $dayjob stuff, like email triage. If not with store and projects, we may just need a *escalate* top level action, though I'm not sure if core wants that.

Cheers,
adric

**Comment by frennkie** [comment]
@rommelfs still interessted in this..?! ;-) I have started implementing this.

**Comment by frennkie** [comment]
@rommelfs PR #562 has been merged and there is now the new `copy` command available in the CLI. Using the `-d` flag you can move a file (and - if desired - also it's children) to another project.

**Comment by Rafiot** [comment]
:+1: & closing :)
