### ISSUE TITLE
debup fails on Python3

### ISSUE THREAD

**Issue by frennkie** [viper-framework/viper#572]
Error

```
[!] The command debup raised an exception:
Traceback (most recent call last):
  File "/home/viper/viper_prod/viper/viper/core/ui/console.py", line 318, in start
    module.run()
  File "/home/viper/viper_prod/viper/viper/modules/debup.py", line 69, in run
    lines = data2.split('\n')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by Rafiot** [comment]
This bug is probably easily fixed this way: ```llnes = data2.split('\n')``` But I bet there are other cases like that.

Can you add a sample file in the test directory?

**Comment by frennkie** [comment]
I'll have to check whether I can upload the sample on which I encountered the issue. There might be (company internal) meta data included in which case I can't upload it. I'll have a look tomorrow.

**Comment by Rafiot** [comment]
oh right. Worst case, I'm sure we can find a sample somewhere.
