### ISSUE TITLE
Issues with yara module pe

### ISSUE THREAD

**Issue by xme** [viper-framework/viper#579]
Hello *,

I'm trying to add more rules to my Yara config on viper. I compiled the latest yara (3.6.0).
But Viper fails to load some config files:

/tmp/index.yara:19839: undefined identifier "pe"

When testing them from the command line, it's ok. Any idea?
I already reinstall the python-yara module...

/x

**Comment by cvandeplas** [comment]
Xavier,

You need to make sure the YARA you run is exactly the same as the one in
yara-python.
Usually a difference in both cause this problem.

**Comment by xme** [comment]
I restarted from zero and removed all the old files / lib from previous yara / python-yara installations. Reinstalled again and, magically, it's ok now!
Tx for the feedback Christophe!
