### ISSUE TITLE
Tests of the APK module are failing

### ISSUE THREAD

**Issue by Rafiot** [viper-framework/viper#589]
This is the stacktrace on travis: https://travis-ci.org/viper-framework/viper/jobs/251812307#L1196

I'm not totally sure, but I assume it is a regression on androquard's side. 

@frennkie in the failing test case, there is a TODO saying the test is known failing: https://github.com/viper-framework/viper/blob/master/tests/modules/test_apk.py#L129 
As it worked before, I guess this line can be removed.

Related bug on androduard's side: https://github.com/androguard/androguard/issues/277

**Comment by frennkie** [comment]
> As it worked before, I guess this line can be removed.

@Rafiot yes, the comment in https://github.com/viper-framework/viper/blob/master/tests/modules/test_apk.py#L129 is no longer valid.. the failing test was fixed when androguard/androguard#228 was merged.

**Comment by Rafiot** [comment]
All good now.
