### ISSUE TITLE
Cannot switch between projects via the web interface

### ISSUE THREAD

**Issue by xme** [viper-framework/viper#600]
I'm usually using the CLI interface but for some specific tasks, I need to use the web one.
I've projects defined, they are listed but when I select an alternative project (other than "default"), the web interface does not switch to the selected one!? 
Any idea?
/x

**Comment by Rafiot** [comment]
The web interface is mostly unmaintained, I don't think any of the current maintainer of Viper use it. No promises anyone will be able to help, sorry.

**Comment by xme** [comment]
Ok. Is it the same for the API? Is there a way to upload a file to a specific project with the API? I don't see anything relevant in the doc: 
https://viper-framework.readthedocs.io/en/latest/usage/web.html#file-add

**Comment by frennkie** [comment]
Unfortunately we don't seem to have anybody able and willing to support the Flask-based Web page and API. The API issue with the projects is documented: https://viper-framework.readthedocs.io/en/latest/known_issues/index.html#the-api-interface-isn-t-fully-aware-of-projects

@kevthehermit started a complete rewrite of the Web site and I added a new API: #534 
But this PR is not yet tested a lot and it would also be great to have at least 1 or 2 more people beside me for supporting it..
