### ISSUE TITLE
Error message with MISP (2.4.77) communication (NewAttributeError)

### ISSUE THREAD

**Issue by Tux-Panik** [viper-framework/viper#608]
Hi all,

Referring to the end of issue #522 , I encounter strange message about missing modules.
I'm using the latest commits of:
- Viper [471dba21c046d9782f5f2adb8680019327131844](https://github.com/viper-framework/viper/commit/471dba21c046d9782f5f2adb8680019327131844).
- PyMISP [8573519adaf2f98593d866e4bd0f0a71b9f38e7d](https://github.com/CIRCL/PyMISP/commit/8573519adaf2f98593d866e4bd0f0a71b9f38e7d).

I run the 2.4.77 MISP version.

* Using Python 2.7, Viper is able to communicate withMISP, but unable to get back MISP event links answers (see below):
![image](https://user-images.githubusercontent.com/22981167/30419867-2bc194dc-9938-11e7-8504-d685297c3a6e.png)

* Using python 3.5 could fix it, but it raises another error, due to missing modules (see below):
![01](https://user-images.githubusercontent.com/22981167/30430873-ef765114-995c-11e7-8eaa-dbfaa6b3a74a.png)

* If I try to solve it, downloading modules with "pip3", it triggers an exception (see below):
![02](https://user-images.githubusercontent.com/22981167/30430911-15e6ffb0-995d-11e7-9c50-bf59911417c2.png)

* Printing "a" in line 448 of pymisp/mispevent.py provides the following (see below):
![image](https://user-images.githubusercontent.com/22981167/30431213-2b3edb8e-995e-11e7-808a-e4b106c2a703.png)

How can I solve this/these issue.s?

Thanks in advance,
Regards,

Julien

**Comment by Rafiot** [comment]
1. python 2.7 failing is weird and not consistent with the travis run, which is awkward
2. Same for the issue with python3 (see travis). Which version of python3 are you using?
3. `print a` is a syntax error in python 3 and should be written `print(a)`

Next step: fix the syntax error (print) and let me know what is printed

**Comment by Tux-Panik** [comment]
2. I'm using version 3.4.3.
3. Changing the syntax to `print(a)`, I have no issue with MISP function (very strange), but still issues with several modules:
![image](https://user-images.githubusercontent.com/22981167/30601786-1a1e63fc-9d63-11e7-9023-dec4b665937f.png)

**Comment by Rafiot** [comment]
That's because some of the deps aren't installed.

```
pip install -r requirements.txt
pip install -r requirements-modules.txt
git submodule init
git submodule update
```

**Comment by Tux-Panik** [comment]
Solved, thanks @Rafiot
