### ISSUE TITLE
Leak of info

### ISSUE THREAD

**Issue by Th4nat0s** [viper-framework/viper#611]
Hello :) 

In the dropdown menu «help» (top right).. the're is a leak of the current page to github.
It leak in some case the file hash :) 

Could you apply a noref here... bye.

**Comment by frennkie** [comment]
Good point - I wasn't aware of this!
I included a fix in my (separate) Django Web branch.

**Comment by Th4nat0s** [comment]
Nice, waiting for it !

**Comment by Th4nat0s** [comment]
Anyone will commit it ?

**Comment by Rafiot** [comment]
Not sure the django web interface is ready to be merged... But if it is, let me know :)

**Comment by frennkie** [comment]
@Rafiot I still think it is a good idea to pursue the path described in #412..
If have been working a bit more on the Django code (Upgrade to Django2 and Bootstrap 4)

**Comment by frennkie** [comment]
If we do a "stable" 1.4 release then it makes sense to fix this security related issue in the Bottle/Flask web site. As the fix is trivial I opened the PR.
