### ISSUE TITLE
Some installation / usage issues

### ISSUE THREAD

**Issue by zTemplar85** [viper-framework/viper#632]
Hi,

Had setup viper on a testing machine. pip3 was used for requirements.txt.
Encounter the message when starting viper.

> Something wrong happened while importing the module viper.modules.pdf: No module named 'viper.modules.pdftools.pdfid'

**Comment by Rafiot** [comment]
Can you try to run ```git submodule init && git submodule update``` and try again

**Comment by Rafiot** [comment]
For pydeep, you will need to install the version from trunk: `pip3 install git+https://github.com/kbandla/pydeep.git`

The documentation on the website is extremely outdated, sorry for that :/ (see: https://github.com/viper-framework/viper/issues/546) but the documentation in the repo (https://github.com/viper-framework/viper/tree/master/docs) is relatively up-to-date. 

If you find issues, we welcome pull requests!

**Comment by zTemplar85** [comment]
When running clamav, I'll get the message 

> Unable to scan file 90cb629b6529ce276ad35a7cda1fe72de1cc13ae85606f67042d1c67a0277a29 with antivirus daemon, 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

When running fuzzy. I'll get the message

>  [!] The command fuzzy raised an exception:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/viper-1.3.dev0-py3.5.egg/viper/core/ui/console.py", line 319, in start
>     module.run()
>   File "/usr/local/lib/python3.5/dist-packages/viper-1.3.dev0-py3.5.egg/viper/modules/fuzzy.py", line 119, in run
>     score = pydeep.compare(__sessions__.current.file.ssdeep, sample.ssdeep)
> TypeError: a bytes-like object is required, not 'str'

I testing out / configuring the rest of the modules meanwhile

**Comment by Rafiot** [comment]
That's what we beg for not having unit tests... Working on it right now.

**Comment by zTemplar85** [comment]
Apologies for this but encountering issue with both clamav and fuzzy.

**fuzzy**
![image](https://user-images.githubusercontent.com/5791182/34701237-f6be7a0c-f521-11e7-9ae8-c7b1824ab042.png)

clamav
![image](https://user-images.githubusercontent.com/5791182/34701254-131c9760-f522-11e7-8460-9ae4c05ab0b8.png)

**Comment by Rafiot** [comment]
This is line 119 in the fuzzy module now: https://github.com/viper-framework/viper/blob/master/viper/modules/fuzzy.py#L119

Can you please git pull the most recent version of viper?

**Comment by zTemplar85** [comment]
Hi, had performed a git pull. Followed by sudo make install.

```
klng5@malyzer:~/viper$ viper-cli
Traceback (most recent call last):
  File "/usr/local/bin/viper-cli", line 4, in <module>
    __import__('pkg_resources').run_script('viper==1.3.dev0', 'viper-cli')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/viper-1.3.dev0-py3.5.egg/EGG-INFO/scripts/viper-cli", line 8, in <module>
    from viper.core.ui import console
  File "/usr/local/lib/python3.5/dist-packages/viper-1.3.dev0-py3.5.egg/viper/core/ui/console.py", line 19, in <module>
    from viper.core.plugins import __modules__
  File "/usr/local/lib/python3.5/dist-packages/viper-1.3.dev0-py3.5.egg/viper/core/plugins.py", line 47, in <module>
    __modules__ = load_modules()
  File "/usr/local/lib/python3.5/dist-packages/viper-1.3.dev0-py3.5.egg/viper/core/plugins.py", line 41, in load_modules
    parser_args=get_argparse_parser_actions(member_object().parser),
  File "/usr/local/lib/python3.5/dist-packages/viper-1.3.dev0-py3.5.egg/viper/modules/misp.py", line 176, in __init__
    known_types = temp_me.known_types
AttributeError: 'MISPEvent' object has no attribute 'known_types'
```

**Comment by Rafiot** [comment]
Right, can you do that: `pip install git+https://github.com/MISP/PyMISP`

I did a few changes in PyMISP that aren't in the most recent tagged version.

**Comment by zTemplar85** [comment]
Working well now :+1:
