### ISSUE TITLE
Delete all exception

### ISSUE THREAD

**Issue by yonilip** [viper-framework/viper#633]
When trying to delete all files, the following exception is thrown.

> viper > delete -a
> Are you sure? It can't be reverted! [y/n] y
> [!] The command delete raised an exception:
> Traceback (most recent call last):
>   File "/home/user/viper/viper/core/ui/console.py", line 312, in start
>     self.cmd.commands[root]['obj'](*args)
>   File "/home/user/viper/viper/core/ui/commands.py", line 330, in run
>     os.remove(get_sample_path(sample.sha256))
> TypeError: remove: path should be string, bytes or os.PathLike, not NoneType

Is this a known issue?

Edit:
still investigating, "get_sample_path" returns None since the path created by sample.sha256 dosent exist.
I didnt manually remove binaries.

**Comment by Rafiot** [comment]
This is weird, I just tested with the latest version (https://github.com/viper-framework/viper/commit/a23623ab7012df1c1e9d58d495dd77a70bc2ab7f) and it worked.

Which version of viper are you using?

**Comment by yonilip** [comment]
I used the latest master.
Although I said I didnt manually remove binaries, I suspect that I might've done something when initially testing the framework out. I decided to remove it and reinstall the framework.
If I meet the problem again Ill add details.

**Comment by Rafiot** [comment]
Thank you very much, I'm closing this bug for now then, please reopen if needed.
