### ISSUE TITLE
Avoid output verbosity in the new release?

### ISSUE THREAD

**Issue by Tux-Panik** [viper-framework/viper#641]
Dear,
I just installed the last commit of Viper-Framework.
I don't know why, I have a verbose output in console when I run "sudo python3 viper-cli"

`sudo python3 viper-cli`
`/usr/local/lib/python3.4/dist-packages/pymisp/mispevent.py:636: DeprecationWarning: Call to deprecated function get_known_types.`
`  def get_known_types(self):`
`/usr/local/lib/python3.4/dist-packages/pymisp/mispevent.py:636: DeprecationWarning: Call to deprecated function get_known_types.`
`  def get_known_types(self):`
`INFO [console.py:108 - start() ] Starting viper-cli`

Verbosity is set to "False" in the relevant viper.conf, so it can't be the origin:
`verbose = False`

I usually ran "viper-cli" using the following command, but with this new version, it doesn't fix the issue: `sudo python3 -W ignore viper-cli`

An idea on how to not display these messages?

Thanks in advance,
Best regards,
Julien

**Comment by Rafiot** [comment]
I need to update the calls to PyMISP in viper... Adding it to the TODO list :)

**Comment by Tux-Panik** [comment]
Thanks Rafiot. It works fine now.
Regards,
Julien
