### ISSUE TITLE
Something wrong happened while importing the module viper.modules.pdf: No module named 'viper.modules.pdftools.pdfid'

### ISSUE THREAD

**Issue by 99anhadi** [viper-framework/viper#655]
![cuplikan layar_2018-02-17_17-23-14](https://user-images.githubusercontent.com/26619526/36340095-437f50c4-1407-11e8-814d-7fa2f958d6f2.png)
How to Fix it?

**Comment by frennkie** [comment]
git submodule init
git submodule update

https://github.com/viper-framework/viper/blob/master/docs/source/installation/index.rst
