### ISSUE TITLE
Installation instructions are out of date and confusing

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#657]
The transition between Python 2.7 and Python 3.x has not been very clear.
The installation documentation at https://github.com/viper-framework/viper/blob/master/docs/source/installation/index.rst has not been properly updated, and trying to now to perform a fresh install is confusing and is leading to issues. For example asking to install the core dependencies through pip should be superfluous if the Makefile should take care of all.
Additionally, the Makefile appears to still be relying on Python 2.7. Even if it would support Python 2.7, there are now dependencies (like Django 2.x) that require necessarily Python 3.x.

I think we need to do a full review of the dependencies and installation process and clean it all up.

**Comment by frennkie** [comment]
I agree. My suggestion would be to move away from the Makefile and rely on the Python setuptools and the setup.py. This will eventually enable us to simply install with `pip install viper-framework` (including all dependencies and so on. I have already started working on this.

**Comment by botherder** [comment]
I agree with that.

**Comment by botherder** [comment]
@Rafiot can you please review this?

**Comment by frennkie** [comment]
@Rafiot yes, I didt.. but I was unsure about how/where to distribute some files (e.g. PEID and default yara rules. 

Another blocking point I ran into is that specifiying requirements in the setup.py works fine for dependencies that can be installed with `pip install` from Pypi. But it did not install all our requirements that point to repositories on Github... :-(  As a hack/workaround I wrote some code that extracts the git repo dependencies and installs them with `pip.main(['install', <repo url>])`. Thisget's the job done.. but I don't like it..

**Comment by botherder** [comment]
For the moment I have fixed some of the issues with the Makefile and the configuration. I would agree that a pip package would be best, but we should probably open a separate ticket on that. @frennkie is there any help we can give you on this?
