### ISSUE TITLE
No module named 'verifysigs'

### ISSUE THREAD

**Issue by mattulm** [viper-framework/viper#665]
ubuntu@ip-10-40-132-25:/srv/viper$ ./viper-cli
[!] Something wrong happened while importing the module viper.modules.sigs_helper.sigs_helper: No module named 'verifysigs'

Tried google-fu for some time to no avail. 
Anyone have an idea on how to solve this?

**Comment by frennkie** [comment]
Sorry.. the official documentation hosted on ReadTheDocs (https://viper-framework.readthedocs.io/en/latest/) is not being updated automaticall... I hope that @botherder can fix this sometime.
 
Please follow https://github.com/viper-framework/viper/blob/master/docs/source/installation/index.rst

**Comment by mattulm** [comment]
My apologies this time. It has been awhile since I have been able to get to this. I ran the newer instructions you gave me, and they worked much better. One slight change, here:

Viper can retrieve files remotely through Tor, if you're interested in such feature you should install SocksiPy:
instead of: 
$ sudo apt-get install python-socksipy
Change to:
$ sudo apt-get install python-socks

I got this error message when I did the first line:
Package python-socksipy is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-socks



When i try and run the web version: ./viper-web
This comes up: ImportError: No module named 'django.urls'

I found something on Stack Exchange, that mentioned this basically:
sudo pip3 install --upgrade django

./viper-web runs with no issues, other than:
[!] There are outstanding Django DB migrations
WARNING - archiver.py:103 - RarExtractor: Missing System dependencies: ['unrar']
WARNING - archiver.py:103 - SevenZipSystemExtractor: Missing System dependencies: ['7z']
WARNING - archiver.py:103 - SevenZipSystemCompressor: Missing System dependencies: ['7z']


I do still get a few module missing errors when i try some things. Others work, but these so far have not:
Missing dependency, install pyclamd (`pip install pyclamd`)
Missing dependency, install pydeep (`pip install pydeep`)

I have done the command with pip, and pip3, but get a notice that the requirement is already satisfied.
Any Ideas? Can't find them in the PATH? ? ? ? ......

**Comment by botherder** [comment]
@frennkie I'm following the latest instructions and yet I encounter the same `verifysigs` issue. Can you clarify what step is missing from the documentation exactly?

**Comment by frennkie** [comment]
@botherder I didn't notice that you updated the docs (https://github.com/viper-framework/viper/commit/520112a5dabe29061fc31a119ef5e9b9db5ce748#diff-31033a26c68004ee937bdad9ec8e736c). 

I usually don't run "sudo make install" (see #614 and #696) but instead:

```
git clone https://github.com/viper-framework/viper
cd viper
sudo pip3 install -r requirements.txt
git submodule init
git submodule update
```

And then either `./viper-cli` or install viper with `sudo pip3 install .`.

**Comment by botherder** [comment]
But the Makefile relies on `setup.py` which should take `requirements-modules.txt` into account. For some reason something fails though.

While I'm not set on necessarily using Makefile for install, it seemed to be the most straightforward install process. Ideally, we should switch to a PyPi package.
