### ISSUE TITLE
Consistent use of hash type to identify file

### ISSUE THREAD

**Issue by geekscrapy** [viper-framework/viper#668]
In the breadcrumbs and in the summary pages the sha256 hash is used, however in the page title the md5 is used. This creates some confusion to which hash is being looked at!

**Comment by botherder** [comment]
True. We tried to unify to sha256 a while ago, but then some stuff was kept to md5 because of spacing/formatting.

**Comment by geekscrapy** [comment]
Totally agree, and I think sha256 is the way forward, multiple commercial tools (Carbon black for instance) still utilise md5 as the primary hash. We also utilise md5 heavily my day job, easier to pass around :)
Maybe a better way to do this would be to truncate the sha256 hash where required:
a3931d...f48aed

Of course, dedupe on sha256 though!!

**Comment by frennkie** [comment]
@geekscrapy What do you mean by "page title"? The only place where I can find the MD5 hash in my Viper installation is the MD5 table row.. Are you using the most current version (master)?
