### ISSUE TITLE
can not find viper web first usage password

### ISSUE THREAD

**Issue by Melwer** [viper-framework/viper#669]
hey guys,

just installed viper on new systems, through all the way i have not set password.
thought maybe there is a default one for first usage.

anyone?

thanks ahead!

**Comment by frennkie** [comment]
You can set the user name (default is admin) and also the password in the viper.conf file.

If this was not set then a random password will be generated for admin and stored on first start.
The easiest way then is to set a new admin user in viper.conf (e.g. admin2) and a password. Then (Re) start viper-web.

On 29 May 2018 03:02:27 GMT+09:00, Aeriusm <notifications@github.com> wrote:
>hey guys,
>
>just installed viper on new systems, through all the way i have not set
>password.
>thought maybe there is a default one for first usage.
>
>anyone?
>
>thanks ahead!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/viper-framework/viper/issues/669

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by botherder** [comment]
I'm closing this for now, but it seems like the process is a bit confusing. Maybe it should be reviewed.

**Comment by frennkie** [comment]
@botherder well.. I didn't want to start with "admin:admin"... an alternative approach would have been to use a default (e.g. admin:admin) and refuse to do anything useful until this is changed.. 
Otherwise people will just start spinning up Viper instances on AWS with default login that can easily be taken over..!? :-/

**Comment by botherder** [comment]
Yes, you are right. I think the general approach is valid, let's just review that the process is clear.
