### ISSUE TITLE
sqlalchemy not found

### ISSUE THREAD

**Issue by DigiAngel** [viper-framework/viper#674]
My process:
~~~
mkdir /opt/viper-venv
cd /opt/viper-venv
git clone https://github.com/viper-framework/viper.git
cd ..
virtualenv viper-venv
. viper-venv/bin/activate
cd viper-venv/viper
pip install -r requirements-base.txt
pip install -r requirements-modules.txt
pip install -r requirements.txt
pip install sqlalchemy
Requirement already satisfied: sqlalchemy in /opt/viper-venv/lib/python2.7/site-packages (1.1.15)
~~~

running viper-cli gives me:
~~~
Traceback (most recent call last):
  File "./viper-cli", line 8, in <module>
    from viper.core.ui import console
  File "/opt/viper-venv/viper/viper/core/ui/console.py", line 18, in <module>
    from viper.core.session import __sessions__
  File "/opt/viper-venv/viper/viper/core/session.py", line 10, in <module>
    from viper.core.database import Database
  File "/opt/viper-venv/viper/viper/core/database.py", line 11, in <module>
    from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text
ImportError: No module named 'sqlalchemy'
~~~

Any assistance would be awesome....struggled to get this to work for a while now.

**Comment by frennkie** [comment]
Please make sure to use Python3 (and pip3) 

On 14 June 2018 19:24:25 CEST, DigiAngel <notifications@github.com> wrote:
>My process:
>~~~
>mkdir /opt/viper-venv
>cd /opt/viper-venv
>git clone https://github.com/viper-framework/viper.git
>cd ..
>virtualenv viper-venv
>. viper-venv/bin/activate
>cd viper-venv/viper
>pip install -r requirements-base.txt
>pip install -r requirements-modules.txt
>pip install -r requirements.txt
>pip install sqlalchemy
>Requirement already satisfied: sqlalchemy in
>/opt/viper-venv/lib/python2.7/site-packages (1.1.15)
>~~~
>
>running viper-cli gives me:
>~~~
>Traceback (most recent call last):
>  File "./viper-cli", line 8, in <module>
>    from viper.core.ui import console
>File "/opt/viper-venv/viper/viper/core/ui/console.py", line 18, in
><module>
>    from viper.core.session import __sessions__
>File "/opt/viper-venv/viper/viper/core/session.py", line 10, in
><module>
>    from viper.core.database import Database
>File "/opt/viper-venv/viper/viper/core/database.py", line 11, in
><module>
>from sqlalchemy import Column, Integer, String, DateTime, ForeignKey,
>Text
>ImportError: No module named 'sqlalchemy'
>~~~
>
>Any assistance would be awesome....struggled to get this to work for a
>while now.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/viper-framework/viper/issues/674

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DigiAngel** [comment]
Worked great thank you....maybe on the front page python3 could be list as a requirement :)  Thanks again.
