### ISSUE TITLE
Download samples from MISP fails

### ISSUE THREAD

**Issue by chpanag** [viper-framework/viper#680]
Hello,
I'm exploring the Viper-MISP integration through the MISP module. While I create successfully an event with a sample malware file attached (using the viper-cli), the module fails to download a sample from a MISP event for analysis.
The exception I get is the following:

`viper viper.conf [MISP 21] > misp download
[!] The command misp raised an exception:
Traceback (most recent call last):
  File "/usr/local/viper/viper/core/ui/console.py", line 319, in start
    module.run()
  File "/usr/local/viper/viper/modules/misp.py", line 639, in run
    self.download()
  File "/usr/local/viper/viper/modules/misp_methods/download.py", line 49, in download
    ok, data = self.misp.download_samples(event_id=event_id)
  File "/usr/local/lib/python3.6/site-packages/pymisp/api.py", line 1173, in download_samples
    unzipped = BytesIO(archive.open(f['filename'], pwd=b'infected').read())
  File "/usr/local/lib/python3.6/zipfile.py", line 1352, in open
    zinfo = self.getinfo(name)
  File "/usr/local/lib/python3.6/zipfile.py", line 1281, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'viper.conf' in the archive"`

This occurs on latest release v1.3 and latest commit of the master branch as well.

**Comment by Rafiot** [comment]
This is weird, it works for me.

Which version of pymisp are you using? 

```
$ (git::master) ipython
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pymisp
In [2]: pymisp.__version__
Out[2]: '2.4.93'
```

**Comment by chpanag** [comment]
I was using 2.4.89 version of pymisp. Upgrade to 2.4.93 solved the issue. Thanks for helping.

**Comment by Rafiot** [comment]
Great, thanks for the feedback :)
