### ISSUE TITLE
The installation doc is missing to install the requirements.txt

### ISSUE THREAD

**Issue by icepaule** [viper-framework/viper#682]
Hello team,

first of all, thanks for the great work you are doing in giving us that excellent tool.
While doing a fresh install on a Ubuntu 18.04, I found **pip3 install -r requirements.txt** missing in the installation doc.
You might want to correct that.  :-)

Cheers
Marcus

**Comment by botherder** [comment]
That step shouldn't be necessary by running `sudo make install` although you are right that the installation docs are rather confusing currently.

**Comment by botherder** [comment]
There is a more general issue opened at #657.
