### ISSUE TITLE
sudo make install fails

### ISSUE THREAD

**Issue by wirehack7** [viper-framework/viper#683]
I'm going through the installation process as described here: https://viper-framework.readthedocs.io/en/latest/installation/

When doing that I get that error:
```
Installed /usr/local/lib/python3.5/dist-packages/six-1.10.0-py3.5.egg
error: The 'six==1.11.0' distribution was not found and is required by viper
Makefile:7: die Regel für Ziel „install“ scheiterte
make: *** [install] Fehler 1
```

I did install six:
``` 
$ pip3 install six==1.11.0
Collecting six==1.11.0
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six
Successfully installed six-1.11.0
```

The error persists.

**Comment by frennkie** [comment]
Can you change this line `six==1.11.0` into `six` in `requirements-base.txt` and try again? 

On 14 August 2018 23:36:21 CEST, "Markus R." <notifications@github.com> wrote:
>I'm going through the installation process as described here:
>https://viper-framework.readthedocs.io/en/latest/installation/
>
>When doing that I get that error:
>```Installed
>/usr/local/lib/python3.5/dist-packages/six-1.10.0-py3.5.egg
>error: The 'six==1.11.0' distribution was not found and is required by
>viper
>Makefile:7: die Regel für Ziel „install“ scheiterte
>make: *** [install] Fehler 1
>```
>
>I did install six:
>``` $ pip3 install six==1.11.0
>Collecting six==1.11.0
>  Cache entry deserialization failed, entry ignored
>  Cache entry deserialization failed, entry ignored
>  Cache entry deserialization failed, entry ignored
>Downloading
>https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
>Installing collected packages: six
>Successfully installed six-1.11.0
>```
>
>The error persists.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/viper-framework/viper/issues/683

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by frennkie** [comment]
I think it's not related to the pinned version of `six`. 

`sudo make install` seems more or less broken to me at the moment. 

You can skip it and run `sudo pip3 install -r requirements.txt` directly to get the dependencies installed and the run viper from the local directory (`./viper-cli` or `./viper-web`).

**Comment by wirehack7** [comment]
With removing version string it works.
I've got another problem now. But that's not part of this topic (wxPython won't install)

**Comment by frennkie** [comment]
make install run this:

``python3 setup.py install --record installed_files.txt`` 

And that seems to have problems with the requirements and some dependencies. I also got a similar error as you, didn't change anything and re-run (twice) `sudo make install` and then it completed without errors...

**Comment by botherder** [comment]
Closing, as Makefile was dropped in favor of pip install.
