### ISSUE TITLE
file upload size limit

### ISSUE THREAD

**Issue by stormyair** [viper-framework/viper#684]
hello,

I'm countering with an issue that files greater then 1024 KBcant upload to viper.
is there any size limit to files upload (via API and web interface)?
where can i change those values?

thanks.

**Comment by frennkie** [comment]
Hi, there is no upload limit.
Technically it's implemented with a temporary file (to avoid memory bound limitations).
Could it be that a tmp die is used that is too small (<1-2MB) on your system..? 

On 15 August 2018 08:44:28 CEST, stormyair <notifications@github.com> wrote:
>hello,
>
>I'm countering with an issue that files greater then 1024 KBcant upload
>to viper.
>is there any size limit to files upload (via API and web interface)?
>where can i change those values?
>
>thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/viper-framework/viper/issues/684

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stormyair** [comment]
thanks. found the problem. it was nginx configuration
