### ISSUE TITLE
Cleaning up Django files

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#692]
I'm not quite happy of the current structure of the viper-web code. Particularly I would like to move some of the Django files (like `manage.py` and the settings) away from the root folder, or find a better order for the application.

Any suggestions?

**Comment by botherder** [comment]
@frennkie any feedback on this?

**Comment by frennkie** [comment]
I recall struggling a bit with exactly this issue...  at the moment there are three files for `Django`:

* settings_local.py.sample
  * The `settings_local.py.sample` is an example file, just like `viper.conf.sample`... it can be moved (e.g. to docs?!) without any problems.
* viper-web
  * I assume you are fine with `viper-web`, right? 
* manage.py
  * `viper-web` actually calls this file (`execute_from_command_line(["manage.py"[...]`)... It might be possible to move it.. although I don't really see what would be gained from this...

**Comment by botherder** [comment]
It is mostly just me being obsessed about cleanliness of codebase.

**Comment by qq854051086** [comment]
@botherder 我不知道我和你的观点是否相同，作为网站开发来讲，我特别感兴趣viper的项目结构。很明显它与我常用的项目结构不太一样，从models来讲就是一个特别的地方，他用了自己创建的ORM，而不是Django的，我很欣赏他的写法，让我对网站开发有了深的认识
