### ISSUE TITLE
Creating a LIEF module

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#693]
Because pefile is falling in disuse, a good alternative would be to create a separate module based on LIEF:
https://github.com/lief-project/LIEF
Or rewrite the Viper `pe` module altogether.

**Comment by Rafiot** [comment]
We rarely reject PR ;)

LIEF has a very simple API that works with all the formats. Also, it can be installed as a python module out-of-the-box, which wasn't the case for radare last time I checked.

**Comment by neriberto** [comment]
> which wasn't the case for radare last time I checked.

Yes, I must agree with it :)

**Comment by dusby** [comment]
This issue can be closed (#735)

**Comment by Rafiot** [comment]
Thanks!
