### ISSUE TITLE
sigs_helper tries to import a missing verifysigs

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#694]
On a fresh install on startup I get:

```[!] Something wrong happened while importing the module viper.modules.sigs_helper.sigs_helper: No module named 'verifysigs'```

In fact `sigs_helper.py` does import this stuff:

```from verifysigs.utils import auth_data
from verifysigs.utils import fingerprint
from verifysigs.utils import pecoff_blob```

`verifysigs` seems to be missing and is not available in requirements or pypi.

**Comment by Rafiot** [comment]
IIRC, it is this one: 

```
pip install git+https://github.com/sebdraven/verify-sigs.git
```

**Comment by botherder** [comment]
Shouldn't that be automatically installed by `setup.py` then?
