### ISSUE TITLE
Create PyPi package and new rolling release model

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#696]
Releasing version of Viper has been an embarrassingly slow and painful process. At this point versioning isn't even really a useful thing.

In order to revive Viper in a more usable software, I think it is necessary that we invest some time in making a PyPi package happen, which could also allow for a proper updating mechanism and that would allow us to remove the `viper-update` utility which is outdated and half-broken.

**Comment by frennkie** [comment]
I started looking into this some time ago.. (e.g. #614) but it's not trivial.. But I think it's definitely worth the effort.

**Comment by botherder** [comment]
As a very first step we need to unify the installation process. Clearly the current `setup.py` has some issues, as not all dependencies are installed. Maybe I can for the moment change Makefile to include all the steps used by @frennkie here https://github.com/viper-framework/viper/issues/665#issuecomment-414399374 which seem to work fine.

The only downside is `sudo pip3 uninstall viper` will only remove Viper's files, and not all the dependencies that were installed for it. Because there are so many dependencies for Viper modules, we need to have a clean way of handling them.

**Comment by botherder** [comment]
With #702 and following commits the pip-based installation process seems to be working. PyPi packages will be uploaded when releases are made.
