### ISSUE TITLE
Update documentation of core commands

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#697]
The documentation is lagging behind and is missing (among many other things I suppose) the documentation that is relevant for a number of console commands that have been added over the time. This includes:

- `analysis`
- `new`
- `parent`
- `rename`
- `stats`

Documentation of some of the existing commands is also out of date as additional options have been added.

**Comment by deralexxx** [comment]
Will take that one and work on it.

**Comment by botherder** [comment]
Thanks! :+1:

**Comment by deralexxx** [comment]
So I reviewed the doc for installation and that looks fine. commands to be done

**Comment by deralexxx** [comment]
so new commands have all been documented, old command review is open....

**Comment by botherder** [comment]
Is this completed now?

**Comment by deralexxx** [comment]
> Is this completed now?

yes

**Comment by botherder** [comment]
Thanks!
