### ISSUE TITLE
Drop support for python2

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#699]
I'm rounding up the current issues that needs to be closed before releasing the 2.0 finally. One issue is some of the lingering code for python2+python3 compatibility, which I would very much like to get rid of. Therefore, I would like to consider the possibility of dropping python2 altogether and require python3 from now on.

Any objections to this?

**Comment by Rafiot** [comment]
None at all. Killing python2 compatibility is my hobby.

**Comment by botherder** [comment]
:+1:

**Comment by botherder** [comment]
I believe all the necessary changes have been made in the documentation. Closing this.
