### ISSUE TITLE
<Need Help> Linking to Cuckoo Ver. 2.0.6 Fails Returned 404

### ISSUE THREAD

**Issue by VoldyRCX** [viper-framework/viper#711]
My viper version:2.0
Cuckoo version:2.0.6
I can submit the file to Cuckoo and the Cuckoo worked.when I click 'Link to latest existing Cuckoo Report'
It returned 404-Not Found
Log:

> - [*] Session opened on /home/rec/.viper/binaries/0/6/c/0/06c0f7d76ab447b3b6a19609555fa5854e9a85c35ce487d755c800f759b5d998
> - 2018-10-20 07:55:46 - django.server - INFO - basehttp.py:124 - "GET /project/default/file/06c0f7d76ab447b3b6a19609555fa5854e9a85c35ce487d755c800f759b5d998/cuckoo/ HTTP/1.1" 200 92
> - 2018-10-20 07:55:48 - django.request - WARNING - log.py:228 - Not Found: /project/default/file/06c0f7d76ab447b3b6a19609555fa5854e9a85c35ce487d755c800f759b5d998/None/analysis/5/summary/
> - 2018-10-20 07:55:48 - django.server - WARNING - basehttp.py:124 - "GET /project/default/file/06c0f7d76ab447b3b6a19609555fa5854e9a85c35ce487d755c800f759b5d998/None/analysis/5/summary/ HTTP/1.1" 404 8814
> -

**Comment by frennkie** [comment]
The "None" in the "Not Found" obviously seems to be a problem. This part of the URL should contain the web URL of your cuckoo installation: `cfg.cuckoo.cuckoo_web` (both this and `cuckoo_host` need to be set).

**Comment by VoldyRCX** [comment]
> The "None" in the "Not Found" obviously seems to be a problem. This part of the URL should contain the web URL of your cuckoo installation: `cfg.cuckoo.cuckoo_web` (both this and `cuckoo_host` need to be set in `viper.conf`).

Thank you very much.I set cuckoo_web & cuckoo_host.It finally worked!
