### ISSUE TITLE
Web UI and Yara module disagree on path for Yara rules

### ISSUE THREAD

**Issue by toomanybananas** [viper-framework/viper#715]
The web UI stores the Yara rules you create in `~/.viper/yara`, but the yarascan module expects rules to be in `~/.viper/data/yara`. Since ~/.viper/data doesn't exist on my system, I'm assuming `~/.viper/yara` is the correct location but didn't want to submit a PR until I confirmed it.

**Comment by botherder** [comment]
@Rafiot Is this closed/fixed or affected by your recent PR merge?

**Comment by Rafiot** [comment]
Yep, good point, that should be fixed by this one: https://github.com/viper-framework/viper/pull/737/commits/1c1717873ed764ad001f31c114b95ccfbe7090a4
