### ISSUE TITLE
Multiple projects are not supported when using mysql

### ISSUE THREAD

**Issue by WilsonZJ** [viper-framework/viper#723]
Firstly, I used Sqlite as database. The find command became very slow when the number of samples get large. In my case, I got 820k of samples at No.1 project named allSamples. I used sql in sqlite3-cli for searching instead.   
Afterwards, I migrated sqlite3 to mysql, but a new problem troubled me. whatever project I opened, viper always use the same mysql DB. If the mysql DB has a large number of data(like 820k), the opening process is extremely slow(In fact, I still can't open it). A truly way to change project is by editing the config file, which is inconvenient.  So is there a way to solve this problem, or it already have but I don't know.
Thanks.

**Comment by botherder** [comment]
Closing this as it is a duplicate of #650.
