### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by axpatito** [viper-framework/viper#728]
Hi everyone, 

It would be great to have a new tag including the work done to migrate all of the codebase to python3. I am currently working on a docker image to automate the Devops process and be able to launch the service as needed, it would be really helpful if a new tag could be made.

Thanks!

**Comment by deralexxx** [comment]
you mean a tag in the github codebase, not within viper, right?

**Comment by axpatito** [comment]
That is correct. A tag that fully supports Python3 officially.

**Comment by botherder** [comment]
Normally we tag for releases, and 2.0 is unfortunately still not completed. Until the full installation process is completed and bugs are resolved, it would probably just cause troubles to create a tag.
