### ISSUE TITLE
Git-based dependencies not working through PyPi install

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#754]
While using `pip3 install .` inside Viper's folder works fine, installing through PyPi does not work and fails with the following error:

```
ERROR: Could not find a version that satisfies the requirement PyTaxonomies (from viper-framework) (from versions: none)
ERROR: No matching distribution found for PyTaxonomies (from viper-framework)
```

We need to investigate how to make this work, so we can wrap up 2.0 and finally release on PyPi.

**Comment by Rafiot** [comment]
Hmmm right, I need to do an actual release on PyPi then.

I'll work on it asap. When do you want to tag v2.0? The dirty fast fix is to make that optional: none of the git-based deps are critical.

**Comment by botherder** [comment]
I'd prefer to figure out a way to make it work, cause I imagine other dependencies that are not MISP-related will cause the same issue.

**Comment by botherder** [comment]
Any thoughts?

At this point I'm wondering whether it makes sense at all to try to install this as a PyPi package, although it would be very convenient.

**Comment by botherder** [comment]
I thought I had resolved, but this is still not working:

```
HTTPError: 400 Client Error: Invalid value for requires_dist. Error: Can't have direct dependency: 'PyMISPGalaxies @ git+https://github.com/MISP/PyMISPGalaxies.git#egg=PyMISPGalaxies' for url: https://upload.pypi.org/legacy/
```

**Comment by botherder** [comment]
Ultimately I think we can't have a PyPi package that depends on non-PyPi packages.

**Comment by Rafiot** [comment]
You're probably right.

I really need to packages these dependencies. But as I cannot really give a timeline for that, I'll probably make these ones optional so we can release a package.

**Comment by botherder** [comment]
What do you think about #767. In that way we could keep a viper package to a core, and then use git+pip commands from Viper to download and install modules.

**Comment by Rafiot** [comment]
Yep, 100% agree.

**Comment by botherder** [comment]
Closing this ticket as I started work on #767.
