### ISSUE TITLE
Is "pyasn1" module requirement too old?

### ISSUE THREAD

**Issue by dragonyy** [viper-framework/viper#755]
In requirements-modules.txt, pyasn1==0.4.5 is inside.

I installed Viper from MISP installation script. It installed scrapy first, and scrapy depends on pyasn1-modules, which asks for pyasn1 greater than 0.4.6. The error message is as following

> ERROR: pyasn1-modules 0.2.6 has requirement pyasn1<0.5.0,>=0.4.6, but you'll have pyasn1 0.4.5 which is incompatible

And after the installation finished, the result to run "pip freeze | grep asn1" is 

> pyasn1==0.4.5
> pyasn1-modules==0.2.6

I don't know whether scrapy will go bad, maybe the authors can decide to make pyasn1 module  
at least 0.4.6 or above?

**Comment by botherder** [comment]
I suppose we should just bump our pyasn1 requirement. I don't think it needs to be at 0.4.5 necessarily.
