### ISSUE TITLE
Module Documentation

### ISSUE THREAD

**Issue by cyber-guy** [viper-framework/viper#758]
I am attempting to add some new modules to Viper and have reviewed the Add New Modules documentation here (https://viper-framework.readthedocs.io/en/latest/customize/index.html), created a sample module in /usr/local/src/viper/viper/modules and ran viper-web, however the module doesn't show as an option in the module dropdown when interacting with a file and the command does not exist when attempting to call it from the CLI. 

What am I missing? 

Also related, the current MISP module is accessible through the CLI but not the Modules dropdown within a file context. Does something specific have to be done to allow modules to be accessible through the Modules dropdown vs just CLI?

**Comment by botherder** [comment]
Are you running viper from the local binary? Or did you install it with pip3?

**Comment by cyber-guy** [comment]
I installed with pip3

**Comment by botherder** [comment]
Did you install it when your module was already present?

**Comment by cyber-guy** [comment]
Before. 

I did just try "sudo pip3 install ." from /usr/local/src/viper and restarted viper-web to see if it would catch the new module, but it didn't.

**Comment by cyber-guy** [comment]
Thanks for the assistance. If anyone else runs into the issue, if Viper is installed with pip, new modules must be added to /usr/local/lib/python3.#/dist-packages/viper/modules.
Adding modules to /usr/local/src/viper/viper/modules and doing a pip install again does not appear to add them to the actual package directory.
