### ISSUE TITLE
Issues with modules 

### ISSUE THREAD

**Issue by Evan-Sa** [viper-framework/viper#768]
~/viper$ viper
[!] Something wrong happened while importing the module modules.misp: No module named 'viper.common.constants'
[!] Something wrong happened while importing the module modules.pdf: No module named 'modules.pdftools'
[!] Something wrong happened while importing the module modules.pe: No module named 'viper.common.constants'
[!] Something wrong happened while importing the module modules.rat: No module named 'viper.common.constants'

**Comment by botherder** [comment]
Thank, we are aware. It is because of ongoing transition to #767.
