### ISSUE TITLE
viper template improvement request -  search_result.html

### ISSUE THREAD

**Issue by cosrah** [viper-framework/viper#772]
the search_result.html need paging.
the code below in your index.html is more useful.

------------------------------------------------------------
`
{% for project in results %}
	{% for item in project.res %}
//
			<td>{{ project.name }}</td>
			<td><a href="{% url 'file-view' project.name item.1 %}">{{ item.0 }}</a></td>
			<td class="mono">{{ item.1 }}</td>
//
	{% endfor %}
{% endfor %}
`
------------------------------------------------------------

**Comment by botherder** [comment]
Viper web was moved here https://github.com/viper-framework/viper-web. Please make any bug reports or feature requests there.
