### ISSUE TITLE
Module pydns moved to py3dns for Python 3

### ISSUE THREAD

**Issue by tjnel** [viper-framework/viper#775]
Running Viper within python3 it looks like the module for pDNS has changed from https://pypi.org/project/pydns/ is now https://pypi.org/project/py3dns/ in Python3

` [!] Something wrong happened while importing the module modules.pdns: No module named 'pypdns'`

**Comment by botherder** [comment]
The imported module is `pypdns` though, not `pydns`.

**Comment by Rafiot** [comment]
Yes, `pypdns` is the correct name.

I'm currently working on getting the testcases to run again, that will make it easier to figure out what is missing.

**Comment by Rafiot** [comment]
Here it is: https://pypi.org/project/pypdns/
