### ISSUE TITLE
Can't found MISP command in the Viper Framework

### ISSUE THREAD

**Issue by yousefhawwari** [viper-framework/viper#776]
![ViperMISP](https://user-images.githubusercontent.com/25611301/72518951-14309c00-385f-11ea-8fb8-e0cd9520f2d6.PNG)

What should i do to integrate the Viper Framework with the MISP ?
(I installed it on the MISP Server but can't found MISP Command in the Viper Framework).

Thank You.

**Comment by Rafiot** [comment]
Yeah, I need to give some move to the MISP module... Hopefully this month.

**Comment by yousefhawwari** [comment]
@Rafiot Thank you, we're waiting ..

**Comment by Rafiot** [comment]
I'll do my best, but I have a bunch of other things on my plate right now.

**Comment by yousefhawwari** [comment]
@Rafiot Okay! Thank you.

**Comment by yousefhawwari** [comment]
Dear @Rafiot  ,

Is there any updates on the framework ?

Best Regards,
Yousef Hawwari

**Comment by Rafiot** [comment]
Hi,

This PR should solve it: https://github.com/viper-framework/viper-modules/pull/2

@botherder: can you give me the access rights on the repo? Or you can merge it directly, please.

**Comment by botherder** [comment]
Merged.

**Comment by Rafiot** [comment]
Thank you!
