### ISSUE TITLE
can't find viper-web anymore

### ISSUE THREAD

**Issue by icepaule** [viper-framework/viper#780]
Hello guys,
sorry, it might be my bad, but after upgrading to the new version I can't find viper-web anymore.
Could it be that it was missing during your last GIT update?

I need web and API for working with ph0neutria.

Thanks a lot
Marcus

**Comment by frennkie** [comment]
Form which version did you come? Which git commit/branch are you using?

**Comment by icepaule** [comment]
Hi frennkie,
a pretty old one I guess.
But I found out already that I have to use a seperate git repository for the web. So right now I'm already configuring it.

Thanks a lot for the help anyway.

Cheers and stay safe.
Marcus

**Comment by frennkie** [comment]
> seperate git repository for the web

What do you mean by that? There was a major re-write of the web interface. But it still a part of this viper repo. https://viper.li/en/latest/usage/web.html

**Comment by wesinator** [comment]
https://viper.li/ website and docs are 403 currently

**Comment by mhouston007** [comment]
I had the same issue with the missing viper-web command. I did a fresh install from both pip and source (followed the commands in the docs) and there is no viper-web command

**Comment by botherder** [comment]
viper-web was split off from the core, and moved here:
https://github.com/viper-framework/viper-web
Currently it's likely not working.
