### ISSUE TITLE
Website viper.li returning HTTP status 403

### ISSUE THREAD

**Issue by Matthiti** [viper-framework/viper#786]
The website is inaccessible, returning an HTTP status 403.

![image](https://user-images.githubusercontent.com/18379304/83326533-0fe8a680-a275-11ea-996f-24a2eccd62b5.png)

**Comment by frennkie** [comment]
Already mentioned in #780. @botherder any way we can support you in fixing this?

**Comment by botherder** [comment]
@frennkie I am not sure actually. I feel it might be an issue with readthedocs.

**Comment by botherder** [comment]
For the moment, I disabled domain on the RTD, so now the documentation can also be available at:
https://viper-framework.readthedocs.io

**Comment by lu-chi** [comment]
I guess README.md update with RTD would be a good step.

**Comment by botherder** [comment]
Fixed in the README.
