### ISSUE TITLE
using apikey to access cuckoo from viper-web

### ISSUE THREAD

**Issue by siftuser** [viper-framework/viper#788]
Hi! 

I'm having trouble with api_token set by vmcloak, while creating cuckoo VMs. Any help, as to how do I configure `viper.conf` to use the `api_token` set in `cuckoo.conf` ? 

```
[cuckoo]
cuckoo_modified = False
cuckoo_host = http://192.168.57.4:8090
api_token = ************
```

I tried both `api_token` & `apikey` as auth param in above `viper.conf`, but no go

On the viper box, I'm seeing this error
```
viper_web - ERROR - views.py:715 - Cuckoo Response Code: 401
```
On the cuckoo box, I see following error
```
2020-10-25 00:58:51,157 [werkzeug] INFO: 192.168.57.3 - - [25/Oct/2020 00:58:51] "GET /tasks/list HTTP/1.1" 401 -
2020-10-25 00:58:51,163 [werkzeug] INFO: 192.168.57.3 - - [25/Oct/2020 00:58:51] "POST /tasks/create/file HTTP/1.1" 401 -
```

**Comment by frennkie** [comment]
Please note that `viper-web` has moved to a dedicated repository: https://github.com/viper-framework/viper-web

As far as I see it the dedicated code in `viper-web` for submitting to Cuckoo does not use the api_token. So with would need to be added through a pull request.
