### ISSUE TITLE
"misp tag -l" -> NameError: name 'Taxonomies' is not defined

### ISSUE THREAD

**Issue by icepaule** [viper-framework/viper#796]
Hello,
whenever using "tag" with the misp statement to retrieve or set a tag, the below error occures.

Could someone please help me?

Thx so much

_viper attachments/813779903208095784/904085162621538304/spoofer.exe > **misp tag -l**
/home/xxx/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'misp.thesoc.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/home/xxx/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'misp.thesoc.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/home/xxx/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'misp.thesoc.eu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
[!] The command misp raised an exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/viper_framework-2.0rc11-py3.6.egg/viper/core/ui/console.py", line 322, in start
    module.run()
  File "/home/xxx/.viper/modules/misp.py", line 664, in run
    self.tag()
  File "/home/xxx/.viper/modules/misp_methods/tag.py", line 20, in tag
    taxonomies = Taxonomies()
**NameError: name 'Taxonomies' is not defined**
viper attachments/813779903208095784/904085162621538304/spoofer.exe >_

**Comment by Rafiot** [comment]
It is because `pytaxonomies` isn't installed. You can run `pip install pytaxonomies` in the virtualenvironment and that should solve it.

**Comment by icepaule** [comment]
You are my hero....!!!
Thx a lot. - Works like a charm.  ;-)
